---
font:
  sans_family: "Noto Sans"
  serif_family: "Noto Serif"
  monospace_family: "FuraMono Nerd Font Mono"
  size: 20
  rofi_size: 10

key_repeat:
  rate: 35

window_manager:
  waybar_minimum_workspace_count: 5

idle_thresholds:
  lock_screen_delay_minutes: 5
  suspend_delay_minutes: 10
  hibernate_delay_minutes: 45

base16:
  day_scheme: gruvbox-dark-hard
  day_scheme_family: gruvbox
  night_scheme: unikitty-dark
  night_scheme_family: unikitty
  schemes_source: "https://github.com/mnussbaum/base16-schemes-source"
  templates_source: "https://github.com/mnussbaum/base16-templates-source"

wallpaper_dir: /usr/share/backgrounds
