# vim:ft=yaml.ansible:
---
- name: Set timezone
  timezone:
    name: "{{ timezone }}"

- name: Set hardware clock timezone to UTC
  timezone:
    hwclock: UTC

- name: Check timedatectl NTP status
  command: timedatectl status
  register: timedatectl_ntp_status
  changed_when: false

- name: Enable timedatectl NTP
  command: timedatectl set-ntp true
  when: "'System clock synchronized: no' in timedatectl_ntp_status.stdout"
