# vim:ft=yaml.ansible:
---
- name: Install AUR packages
  package:
    state: present
    name:
      - browserpass
      - browserpass-firefox
      - pass-systemd-cred-server

- name: Install pass credential template socket unit
  copy:
    src: pass-credential@.socket
    dest: /etc/systemd/user/pass-credential@.socket

- name: Install pass credential template service unit
  copy:
    src: pass-credential@.service
    dest: /etc/systemd/user/pass-credential@.service

- name: Install ask-password agent dependencies
  package:
    state: present
    name:
      - inotify-tools
      - zenity

- name: Install ask-password agent
  copy:
    src: ask-password-agent
    dest: /usr/local/bin/ask-password-agent
    mode: "0755"

- name: Install ask-password agent service unit
  copy:
    src: ask-password-agent.service
    dest: /etc/systemd/system/ask-password-agent.service

- name: Install ask-password agent preset
  copy:
    src: 80-ask-password.preset
    dest: /usr/lib/systemd/system-preset/80-ask-password.preset

- name: Create GTK config dir for ask-password agent
  file:
    path: /etc/ask-password-agent/gtk-3.0
    state: directory
  tags: [base16]

- name: Render base16 GTK color overrides for ask-password agent
  template:
    src: ask-password-agent.gtk.css.j2
    dest: /etc/ask-password-agent/gtk-3.0/gtk.css
  tags: [base16]
