# vim:ft=yaml.ansible:
---
- name: Install AUR packages
  package:
    state: present
    name:
      - browserpass
      - browserpass-firefox
      - pass-systemd-cred-server

- name: Install pass credential template socket unit
  copy:
    src: pass-credential@.socket
    dest: /etc/systemd/user/pass-credential@.socket

- name: Install pass credential template service unit
  copy:
    src: pass-credential@.service
    dest: /etc/systemd/user/pass-credential@.service
