# vim:ft=yaml.ansible:
---
- name: Install pacakges
  package:
    state: present
    name:
      - greetd
      - greetd-gtkgreet

- name: Check greeter system user
  command: systemd-sysusers --dry-run /usr/lib/sysusers.d/greetd.conf
  register: sysusers_dry
  changed_when: false

- name: Create greeter system user
  command: systemd-sysusers /usr/lib/sysusers.d/greetd.conf
  when: sysusers_dry.stdout != "" or sysusers_dry.stderr != ""

- name: Create config dir
  file:
    path: /etc/greetd
    state: directory
    mode: "0755"

- name: Install config files
  copy:
    src: "greetd-{{ item }}"
    dest: "/etc/greetd/{{ item }}"
  with_items:
    - config.toml
    - environments

- name: Install templated files
  tags: [base16]
  template:
    src: greetd-{{ item }}.j2
    dest: /etc/greetd/{{ item }}
    mode: "0644"
  with_items:
    - sway-config
    - style.css

- name: Install systemd preset
  copy:
    src: 80-greeter.preset
    dest: /usr/lib/systemd/system-preset/80-greeter.preset


