# vim:ft=yaml.ansible:
---
- name: Install pacakges
  package:
    state: present
    name:
      - greetd
      - greetd-gtkgreet

- name: Create config dir
  file:
    path: /etc/greetd
    state: directory
    owner: greeter
    group: greeter
    mode: u=rwX,g=rwX,o=rwX

- name: Install config files
  copy:
    src: "greetd-{{ item }}"
    dest: "/etc/greetd/{{ item }}"
    owner: greeter
    group: greeter
  with_items:
    - config.toml
    - environments

- name: Install templated files
  tags: [base16]
  template:
    src: greetd-{{ item }}.j2
    dest: /etc/greetd/{{ item }}
    owner: greeter
    group: greeter
    mode: "0644"
  with_items:
    - sway-config
    - style.css

- name: Install WM start commands
  copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: a+x
  with_items:
    - start-sway

- name: Enable greetd service
  systemd:
    enabled: true
    name: greetd
    daemon-reload: true
