#! /bin/bash

set -o errexit
set -o nounset

if command -v redshift-period > /dev/null ; then
  appearance=$(redshift-period)
else
  appearance="night"
fi

ansible_args=$@
if [[ -z "${NO_ASK_BECOME_PASS:-}" ]] ; then
  ansible_args="$ansible_args --ask-become-pass"
fi


exec ansible-playbook playbook.yml --verbose --inventory hosts.yml \
  --limit $(hostname) --extra-vars "appearance=$appearance" $ansible_args
