#! /bin/bash

set -o errexit
set -o nounset

source _bootstrap.sh

# cp -r /run/archiso/bootmnt/arch-ansible .
# parted --align optimal /dev/sda
# > unit MiB
# > mklabel gpt
# > mkpart primary fat32 1MiB 261MiB
# > set 1 esp on
# > name 1 "EFI"
# > mkpart primary ext4 261MiB 773MiB
# > name 2 "Grub"
# > mkpart primary ext4 773MiB 100%
# > name 3 "Arch Root"
# mkfs.vfat -F32 /dev/sda1

hostname="qemu"
username="mnussbaum"
disk="/dev/sda"
ssid=""
wireless_card=""

bootstrap "$hostname" "$username" "$disk" "$ssid" "$wireless_card"

# After rebooting:
# sudo systemctl start NetworkManager
# sudo cp -r /root/arch-ansible ~/src
# cd arch-ansible
# ./ansible # This should succeed to the point of secret setup
# gpg --import ~/gpg-keys/private-key.asc
# gpg --import ~/gpg-keys/public-key.asc
# rm -rf ~/gpg-keys
# shutdown -r now # Amongst other reasons this activates gpg-agent
# ssh-add  # Adds SSH key to gpg-agent
# ./ansible
