# vim:ft=yaml.ansible:
---
- name: Setup pi SD card to use as root for an nspawn container, and start the container
  import_playbook: build-pi-container.yml
  tags: [bootstrap]

- hosts: all
  tasks:
    # Currently using a locally modified version of the machinectl plugin
    # due to https://github.com/tomeon/ansible-connection-machinectl/issues/10
    - name: Switch connection to machinectl
      set_fact:
        ansible_connection: machinectl
      tags: [bootstrap]

- name: Run normal bootstrapping from inside the container
  import_playbook: playbook.yml

- hosts: all
  tasks:
    - name: Switch connection back to local for cleanup
      set_fact:
        ansible_connection: local
      tags: [bootstrap]

- name: Cleanup the pi container and mounts
  import_playbook: cleanup-pi-container.yml
  tags: [bootstrap, cleanup]
  when: no_clean is not defined
