# vim:ft=yaml.ansible:
---
- hosts: all
  tasks:
    - import_role:
        name: network_configuration
        tasks_from: runtime
    - import_role:
        name: brightness
        tasks_from: runtime
    - import_role:
        name: qemu-guest
      when: qemu_guest
