# vim:ft=yaml.ansible:
---
# Runs tasks once, when a machine is first booted. Should be used for
# machine configuration specific to a runtime role. It's preferable to put
# tasks in the postinst-playbook.yml file to execute them at image build time
# to keep machine provisioning fast and reliable
- hosts: all
  tasks:
    - import_role:
        name: user
        tasks_from: firstboot
    - import_role:
        name: network_configuration
        tasks_from: runtime
    - import_role:
        name: brightness
        tasks_from: runtime
    - import_role:
        name: qemu-guest
      when: qemu_guest
    - import_role:
        name: qemu-host
      when: qemu_host
