#! /bin/bash

set -o errexit
set -o nounset

hostname=$1
shift
username=$1
shift

echo $hostname > /etc/hostname

sed -i "/en_US.UTF-8/ s/# *//" /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf
export LANG=en_US.UTF-8
ln -sf /usr/share/zoneinfo/America/Los_Angeles /etc/localtime

hwclock --systohc --utc

pacman -Syu --noconfirm ansible python python-passlib vim zsh
