#! /bin/bash

set -o errexit
set -o nounset

if [ -n "${1:-}" ] ; then
  root_device=$1
  shift
else
  root_device="/dev/mapper/vgcrypt-root"
fi

if [ -n "${1:-}" ] ; then
  ssd_device=$1
  shift
else
  ssd_device="/dev/nvme0n1p8"
fi

ansible-playbook playbook.yml -v --ask-become-pass \
  -e '{"monitor": {"name": "eDP-1", "height": 165, "width": 294, "dpi": 276}}' \
  -e root_device=$root_device \
  -e ssd_device=$ssd_device \
  $@
