#! /bin/bash

set -o errexit
set -o nounset

ansible-playbook -i localhost playbook.yml -v \
  --ask-become-pass \
  -e dpi=276 \
  -e root_device=/dev/mapper/vgcrypt-root \
  -e ssd_device=/dev/nvme0n1p8
