# vim:ft=yaml.ansible:
---
- name: Create homed user
  community.general.homectl:
    name: "{{ user.name }}"
    state: present
    storage: directory
    shell: "{{ user.shell }}"
    groups: "wheel,input,pcscd,docker"
    password: "{{ user.password }}"
