# vim:ft=yaml.ansible:
---
- name: Create wheel group
  group: name=wheel state=present

- name: Configure sudoers
  copy:
    src: "ansible_sudoers"
    dest: /etc/sudoers.d/ansible
    validate: "/usr/bin/visudo -cf %s"

- name: Create individual user group
  group:
    name: "{{ user.group }}"
    state: present

- name: Create user
  user:
    name: "{{ user.name }}"
    group: "{{ user.group }}"
    groups:
      - "{{ user.group }}"
      - input
      - wheel
    password: "{{ user.password | password_hash('sha512') }}"
    shell: "{{ user.shell }}"
    update_password: on_create
    append: true

