# vim:ft=yaml.ansible:
---
- name: Install packages
  package:
    state: present
    name:
      - xdg-user-dirs

- name: Install systemd user preset
  copy:
    src: 80-user.preset
    dest: /usr/lib/systemd/user-preset/80-user.preset

- name: Create wheel group
  group: name=wheel state=present

- name: Configure sudoers
  copy:
    src: "ansible_sudoers"
    dest: /etc/sudoers.d/ansible
    validate: "/usr/bin/visudo -cf %s"

- name: Create skel .zshrc to suppress zsh-newuser-install
  copy:
    content: ""
    dest: /etc/skel/.zshrc
    force: false

- name: Create skel Projects dir
  file:
    path: /etc/skel/Projects
    state: directory

- name: Create skel .local/share dir
  file:
    path: /etc/skel/.local/share
    state: directory

- name: Symlink password-store into skel .local/share
  file:
    path: /etc/skel/.local/share/password-store
    src: /usr/share/password-store
    state: link
    force: true

- name: Symlink password-store into skel .password-store
  file:
    path: /etc/skel/.password-store
    src: /usr/share/password-store
    state: link
    force: true

- name: Install PAM system-auth with systemd-homed support
  copy:
    src: system-auth
    dest: /etc/pam.d/system-auth

- name: Install nsswitch.conf
  copy:
    src: nsswitch.conf
    dest: /etc/nsswitch.conf

- name: Install systemd preset
  copy:
    src: 80-homed.preset
    dest: /usr/lib/systemd/system-preset/80-homed.preset
