# vim:ft=yaml.ansible:
---
- name: Create systemd-resolved config directory
  file:
    path: "{{ network_install_root }}/usr/lib/systemd/resolved.conf.d"
    state: directory

- name: Configure nameservers
  copy:
    src: resolved-dns-servers.conf
    dest: "{{ network_install_root }}/usr/lib/systemd/resolved.conf.d/dns_servers.conf"


- name: Install wpa-psk script
  copy:
    src: wpa-psk
    dest: /usr/lib/arch-ansible/bin/wpa-psk
    mode: a+x

- name: Generate WPA PSKs
  shell: "/usr/lib/arch-ansible/bin/wpa-psk --iwd '{{ item.ssid }}' '{{ item.psk }}'"
  register: wpa_psk_outputs
  no_log: true
  changed_when: false
  when: item.psk is defined
  loop: "{{ wifi_networks | default([]) }}"

- name: Dictionarize WPA PSK outputs
  set_fact:
    wpa_psks: "{{ wpa_psks | default({}) | combine({item.item.ssid: item.stdout}) }}"
  loop: "{{ wpa_psk_outputs.results | default([]) }}"
  no_log: true
  when: item is not skipped

- name: Dictionarize SSIDs
  set_fact:
    iwd_config_file_names: "{{ iwd_config_file_names | default({}) | combine({item.ssid: item.ssid}) }}"
  changed_when: false
  no_log: true
  loop: "{{ wifi_networks | default([]) }}"

- name: Generate hex-encoded iwd config file names for SSIDs with special characters
  shell: "echo -n '{{ item.ssid }}' | od --address-radix=n --format=x1"
  register: hex_encoded_ssids
  changed_when: false
  no_log: true
  when: item.ssid is not regex('^[a-zA-Z0-9 \-_]+$')
  loop: "{{ wifi_networks | default([]) }}"

- name: Override iwd config file names for hex-encoded SSIDs
  set_fact:
    iwd_config_file_names: "{{ iwd_config_file_names | combine({item.item.ssid: '=' + item.stdout | replace(' ', '')}) }}"
  changed_when: false
  no_log: true
  when: item is not skipped
  loop: "{{ hex_encoded_ssids.results }}"

- name: Generate iwd config file extensions for PSK networks
  set_fact:
    iwd_config_file_extensions: "{{ iwd_config_file_extensions | default({}) | combine({item.ssid: 'psk'}) }}"
  changed_when: false
  no_log: true
  when: item.psk is defined
  loop: "{{ wifi_networks | default([]) }}"

- name: Generate iwd config file extensions for EAP networks
  set_fact:
    iwd_config_file_extensions: "{{ iwd_config_file_extensions | default({}) | combine({item.ssid: '8021x'}) }}"
  changed_when: false
  no_log: true
  when: item.eap is defined
  loop: "{{ wifi_networks | default([]) }}"

- name: Generate iwd config file extensions for open networks
  set_fact:
    iwd_config_file_extensions: "{{ iwd_config_file_extensions | default({}) | combine({item.ssid: 'open'}) }}"
  changed_when: false
  no_log: true
  when: item.psk is not defined and item.eap is not defined
  loop: "{{ wifi_networks | default([]) }}"

- name: Create network config dirs
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ network_install_root }}/var/lib/iwd"
    - "{{ network_install_root }}/etc/iwd"
    - "{{ network_install_root }}/etc/wireguard"

- name: Configure iwd networks
  template:
    src: iwd_network.conf.j2
    dest: "{{ network_install_root }}/var/lib/iwd/{{ iwd_config_file_names[item.ssid] }}.{{ iwd_config_file_extensions[item.ssid] }}"
  no_log: true
  loop: "{{ wifi_networks | default([]) }}"

- name: Install iwd main config
  copy:
    src: iwd_main.conf
    dest: "{{ network_install_root }}/etc/iwd/main.conf"

- name: Install udev rule to start iwd on wireless device
  copy:
    src: 90-iwd-on-wireless.rules
    dest: "{{ network_install_root }}/usr/lib/udev/rules.d/90-iwd-on-wireless.rules"

- name: Install systemd-networkd config for the primary interface
  copy:
    src: 25-primary.network
    dest: "{{ network_install_root }}/usr/lib/systemd/network/25-primary.network"

- name: Install resume fix IPv6 flush service
  copy:
    src: wireless-resume-ipv6-flush.service
    dest: "{{ network_install_root }}/usr/lib/systemd/system/wireless-resume-ipv6-flush.service"

- name: Install systemd-networkd config for eth0 interface
  copy:
    src: systemd-networkd-eth0-config.network
    dest: "{{ network_install_root }}/usr/lib/systemd/network/eth0.network"

- name: Install networking.target
  copy:
    src: networking.target
    dest: "{{ network_install_root }}/usr/lib/systemd/system/networking.target"

- name: Create drop-in dirs for networking.target PartOf
  file:
    path: "{{ network_install_root }}/usr/lib/systemd/system/{{ item }}.d"
    state: directory
  loop:
    - iwd.service
    - systemd-networkd.service
    - systemd-resolved.service

- name: Install networking.target PartOf drop-ins
  copy:
    src: networking-target-part-of.conf
    dest: "{{ network_install_root }}/usr/lib/systemd/system/{{ item }}.d/networking-target-part-of.conf"
  loop:
    - iwd.service
    - systemd-networkd.service
    - systemd-resolved.service
