# vim: ft=dosini
# Encrypts the home partition too, for organizations that set
# full_disk_encryption (ansible/group_vars/all/organizations.yml). bin/build-image
# enables it. The default initrd gets the matching mkosi.initrd.conf profile.

[Content]
KernelCommandLine=
    systemd.image_policy=esp=unprotected:xbootldr=unprotected+unused+absent:usr=signed:root=encrypted+absent:swap=encrypted+unused+absent:home=encrypted+absent:=ignore
