# vim:ft=yaml.ansible:
---
# TODO: Cut over to sysctl.d dir once geerlingguy.swap supports it
- name: Create /etc/sysctl.conf
  copy:
    content: ""
    dest: /etc/sysctl.conf
    force: false
    mode: "0600"

# TODO: Cut over to ansible-galaxy install of geerlingguy.sway once
# https://github.com/geerlingguy/ansible-role-swap/pull/61 is merged

# TODO: Set vmf cache pressure to 1 to improve perf
- name: Configure swapfile
  include_role:
    name: geerlingguy.swap
    apply:
  vars:
    ansible_    swap_file_path: /swapfile
    swap_file_size_mb: "{{ 16 * 1024 }}"
    swap_swappiness: "1"

- name: Get swapfile offset
  shell: filefrag -v /swapfile | awk '{gsub(/\./,""); if($1=="0:"){print $4}}'
  register: swapfile_offset
  changed_when: false
