# vim:ft=yaml.ansible:
---
- name: AV | Install packages
  become: true
  package:
    name:
      - alsa-utils
      - pulseaudio
      - pulseaudio-alsa
      - pavucontrol
      - gst-libav
      - spotify
      - playerctl
      - lollypop
      - mpv
    state: present

- name: AV | Create mpv config
  copy:
    src: files/mpv.conf
    dest: "{{ user_config_dir }}/mpv/mpv.conf"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
