# vim:ft=yaml.ansible:
---
- name: AV | Install packages
  become: true
  package:
    name:
      - alsa-utils
      - pipewire
      - pipewire-alsa
      - pipewire-docs
      - pipewire-pulse
      - pavucontrol
      - gstreamer
      - gstreamer-vaapi
      - gst-plugins-good
      - gst-libav
      - spotify
      - playerctl
      - wireplumber
      - lollypop
      - mpv
      - xdg-desktop-portal
      - xdg-desktop-portal-wlr
    state: present

- name: AV | Create wireplumber config dirs
  become: true
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/wireplumber
    - /etc/wireplumber/bluetooth-lua.d

- name: AV | Create wireplumber config to enable high quality bluetooth codecs
  become: true
  copy:
    src: files/wireplumber-bluez-config.lua
    dest: /etc/wireplumber/bluetooth-lua.d/51-bluez-config.luad

- name: AV | Install headphone profile toggle script
  become: true
  copy:
    src: files/toggle-headphone-profile
    dest: /usr/local/bin/toggle-headphone-profile
    mode: a+x

- name: AV | Create mpv config dir
  file:
    path: "{{ user_config_dir }}/mpv"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: directory

- name: AV | Create mpv config
  copy:
    src: files/mpv.conf
    dest: "{{ user_config_dir }}/mpv/mpv.conf"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
