# vim:ft=yaml.ansible:
---
- name: Audio | Install pacakges
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - alsa-utils
    - pulseaudio
    - pulseaudio-alsa
    - pavucontrol
