# vim:ft=yaml.ansible:
---
- name: AV | Install packages
  become: true
  package:
    name:
      - alsa-utils
      - pipewire
      - pipewire-alsa
      - pipewire-docs
      - pipewire-pulse
      - pavucontrol
      - gstreamer
      - gstreamer-vaapi
      - gst-plugins-good
      - gst-libav
      - spotify
      - playerctl
      - lollypop
      - mpv
      - xdg-desktop-portal
      - xdg-desktop-portal-wlr
    state: present

- name: AV | Create mpv config
  copy:
    src: files/mpv.conf
    dest: "{{ user_config_dir }}/mpv/mpv.conf"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
