# vim:ft=yaml.ansible:
---
- name: backup | Install packages
  package:
    state: present
    name:
      - fuse2
      - restic

- name: backup | Install restic backblaze backup script
  become: true
  copy:
    src: files/restic-backblaze-backup
    dest: /usr/local/bin/restic-backblaze-backup
    mode: a+x

# To take a backup:
#
# * sudo mount /dev/sda1 /tmp/usb
# * sudo restic --repo /tmp/usb backup ~/{Desktop,Documents,Sync,.password-store,.ssh,.gnupg}
#
# TODO:
#
# * Add systemd scheduled task to regularly execute the backup script
# * Make the script configurable to work with a local USB backup in addition to
#   the cloud
# * Get the backblaze configuration into terraform. Connect ansible to TF output
#   to pull the bucket name
# * Script the seeding of data during initial bootstrapping by restoring from
#   a backup
# * Make the backup script pull data from systemd-creds, and integrate
#   systemd-creds with pass. And trigger a system notification about why I'm
#   being prompted to decrypt
