# vim:ft=yaml.ansible:
---
- name: boot | Run os-prober to find other OS
  command: os-prober
  become: true
  changed_when: false
  notify:
    - Regenerate grub.cfg

- name: boot | Get power_image size
  command: cat /sys/power/image_size
  register: power_image_size_bytes
  changed_when: false

- name: boot | Create /etc/sysctl.conf
  become: true
  copy:
    content: ""
    dest: /etc/sysctl.conf
    force: no
    mode: 0600

# TODO: This fails because the role uses fallocate and creates  a swapfile with
# holes. Need to use dd instead
- name: boot | Configure swapfile
  include_role:
    name: ansible-swapfile
    apply:
      become: true
  vars:
    ansible_become: true
    swapfile_location: /swapfile
    swapfile_size: "{{ ((power_image_size_bytes.stdout | int) * 1.25) | int }}"
    swapfile_swappiness: 1
    swapfile_vfs_cache_pressure: 1

- name: boot | Get swapfile offset
  shell: filefrag -v /swapfile | awk '{gsub(/\./,""); if($1=="0:"){print $4}}'
  register: swapfile_offset
  changed_when: false
  become: true

- name: Identify root partition
  set_fact:
    root_partition: "{{ item }}"
  loop: "{{ desired_partitions }}"
  when: item.name == "Arch Root"

- name: boot | Configure grub
  become: true
  notify:
    - Regenerate grub.cfg
  template:
    src: templates/grub.j2
    dest: /etc/default/grub

- name: boot | Create kernel module directory
  become: true
  file:
    path: /etc/modprobe.d
    state: directory

- name: boot | Configure kernel modules
  become: true
  notify:
    - Regenerate mkinitcpio ramdisk
  copy:
    src: "{{ item }}"
    dest: "/etc/modprobe.d/{{ item | basename }}"
  with_fileglob:
    - files/modprobe.d/*

- name: boot | Install grub
  when: bootstrap is defined and bootstrap == "true"
  notify:
    - Regenerate grub.cfg
  command: >
    grub-install --target=x86_64-efi
                 --efi-directory=/boot/efi
                 --bootloader-id=arch_grub

- name: boot | Install mkinitcpio.conf
  become: true
  notify:
    - Regenerate mkinitcpio ramdisk
  copy:
    src: files/mkinitcpio.conf
    dest: /etc/mkinitcpio.conf
