# vim:ft=yaml.ansible:
---
- name: Brightness | Install packages
  become: true
  package:
    state: present
    name:
      - wl-gammarelay
      - brightnessctl
      - upower

- name: Brightness | Install day-or-night binary
  become: true
  copy:
    src: files/day-or-night
    dest: /usr/local/bin/day-or-night
    mode: a+x

- name: Brightness | Install wl-gammarelay service
  copy:
    src: files/wl-gammarelay.service
    dest: "{{ user_config_dir }}/systemd/user/wl-gammarelay.service"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: Brightness | Enable wl-gammarelay service
  service:
    name: wl-gammarelay.service
    enabled: yes
    state: started
    scope: user
    daemon-reload: true
  become: true
  become_user: "{{ user.name }}"

- name: Brightness | Install colorscheme-changer binary
  become: true
  copy:
    src: files/colorscheme-changer
    dest: /usr/local/bin/colorscheme-changer
    mode: a+x

- name: Brightness | Install colorscheme-changer service
  copy:
    src: files/colorscheme-changer.service
    dest: "{{ user_config_dir }}/systemd/user/colorscheme-changer.service"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: Brightness | Install colorscheme-changer timer
  copy:
    src: files/colorscheme-changer.timer
    dest: "{{ user_config_dir }}/systemd/user/colorscheme-changer.timer"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: Brightness | Enable colorscheme-changer timer
  service:
    name: colorscheme-changer.timer
    enabled: yes
    state: started
    scope: user
    daemon-reload: true
  become: true
  become_user: "{{ user.name }}"

# The ansible copy module doesn't work on this device file :/
# https://forum.floydhub.com/t/error-invalid-cross-device-link-when-copy-file-from-input-to-output-with-os-rename/100/3
- name: Brightness | Lengthen keyboard backlight timeout
  become: true
  shell: echo 1m > /sys/devices/platform/dell-laptop/leds/dell::kbd_backlight/stop_timeout
  when: ansible_system_vendor == "Dell Inc." and lookup("file", "/sys/devices/platform/dell-laptop/leds/dell::kbd_backlight/stop_timeout") != "1m"
