# vim:ft=yaml.ansible:
---
- name: Brightness | Install packages
  become: true
  package:
    state: present
    name:
      - calise-git
      - illum-git
      - redshift-wlr-gamma-control-git

- name: Brightness | Install redshift config
  template:
    src: templates/redshift.conf.j2
    dest: "/home/{{ user.name }}/.config/redshift.conf"
    owner: "{{ user.name }}"

- name: Brightness | Install redshift service
  copy:
    src: files/redshift.service
    dest: "/home/{{ user.name }}/.config/systemd/user/redshift.service"
    owner: "{{ user.name }}"

- name: Brightness | Enable redshift service
  become: true
  become_user: "{{ user.name }}"
  when: window_manager == "i3"
  systemd:
    enabled: true
    name: redshift.service
    scope: user
    daemon-reload: true

- name: Brightness | Install calise config for screen auto-brightness
  become: true
  copy:
    src: files/calise.conf
    dest: /etc/calise.conf

- name: Brightness | Install calised.service config
  copy:
    src: calised.service
    dest: /etc/systemd/system/calised.service
  become: true

- name: Brightness | Enable calise service
  become: true
  when: ansible_virtualization_role != "guest"
  systemd:
    enabled: true
    name: calised.service
    daemon-reload: true

- name: Brightness | Enable illum service for backlight keys
  become: true
  when: ansible_virtualization_role != "guest"
  systemd:
    enabled: true
    name: illum.service
    daemon-reload: true
