# vim:ft=yaml.ansible:
---
# Run v4l2ucp to tweak video inputs if colors look wrong.
# I needed to enable whitebalance_temperature_auto once on the XPS 13. Ideally
# I'd persist the fix to some config file but I can't figure out what file that
# would be
- name: Camera | Install packages
  become: true
  package:
    state: present
    name:
      - v4l2ucp
      - libcamera
      - gst-plugin-libcamera
      - pipewire-libcamera
      - libcamera-tools
      - libcamera-ipa
      - intel-ivsc-firmware
