# vim:ft=yaml.ansible:
---
- name: DevOps | Enable loop kernel module
  become: true
  notify:
    - Regenerate mkinitcpio ramdisk
  copy:
    content: loop
    dest: /etc/modules-load.d/loop.conf

- name: DevOps | Install packages
  become: yes
  package:
    state: present
    name:
      - docker
      - docker-compose
      - etcd
      - kubectl-bin
      - rancher-k3d-bin
      - kubectx
      - helm
      - stern
      - terraform
      - redis

- name: DevOps | Add user to docker group
  become: true
  user:
    name: "{{ user.name }}"
    groups: docker
    append: true

- name: DevOps | Create docker config dir
  file:
    path: /etc/docker
    state: directory
  become: true

- name: DevOps | Enable overlay2 driver
  become: true
  copy:
    src: files/docker-daemon.json
    dest: /etc/docker/daemon.json

- name: Docker | Enable docker service socket activation
  become: true
  systemd:
    enabled: true
    name: docker.socket
