# vim:ft=yaml.ansible:
---
- name: Dropbox | Stop auto-upgrading and restart cycle
  file:
    path: "/home/{{ user.name }}/.dropbox-dist"
    state: directory
    mode: "0000"

- name: Dropbox | Install packages
  package:
    state: present
    name:
      - dropbox
      - dropbox-cli
  become: true

- name: Dropbox | Enable Dropbox user service
  become: true
  become_user: "{{ user.name }}"
  when: ansible_virtualization_role != "guest"
  systemd:
    enabled: true
    name: dropbox.service
    user: true
    daemon-reload: true
