# vim:ft=yaml.ansible:
---
- name: Frontend-dev | Install packages
  package:
    state: present
    name:
      - npm
      - javascript-typescript-langserver
      - prettier
      - vscode-css-languageserver-bin
      - vscode-html-languageserver
  become: true
