# vim:ft=yaml.ansible:
---
- name: Git | Download delta themes
  get_url:
    url: https://raw.githubusercontent.com/dandavison/delta/master/themes.gitconfig
    dest: "{{ user_data_dir }}/delta-themes.gitconfig"

- name: Git | Install delta diff tool
  package:
    name:
      - git-delta
      - mergiraf
    state: present
  become: true

- name: Git | Install gitconfig
  template:
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    src: templates/gitconfig.j2
    dest: "{{ user_home_dir }}/.gitconfig"

- name: Git | Create config dir
  file:
    path: "{{ user_config_dir }}/gitconfig"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: directory

- name: Git | Install personal gitconfig
  template:
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    src: templates/personal-gitconfig.j2
    dest: "{{ user_config_dir }}/gitconfig/personal"

- name: Git | Install eeek gitconfig
  copy:
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    src: files/eeek-gitconfig
    dest: "{{ user_config_dir }}/gitconfig/eeek"

- name: Git | Install attributes file for mergiraf
  copy:
    src: files/gitattributes
    dest: "{{ user_config_dir}}/gitconfig/attributes"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
