# vim:ft=yaml.ansible:
---
- name: global environment configuration | Install /etc/environment
  template:
    src: templates/etc_environment.j2
    dest: /etc/environment
  become: true

- name: global environment configuration | Install /etc/locale.conf
  copy:
    src: files/etc_locale.conf
    dest: /etc/locale.conf
  become: true

- name: global environment configuration | Install shell profile files
  become: true
  copy:
    dest: "/etc/profile.d/{{ item | basename }}"
    src: "{{ item }}"
    mode: "u=rwx,g=rx,o=rx"
  with_fileglob:
    - files/profile.d/*

- name: global environment configuration | Find gem path
  shell: gem environment gempath
  register: gem_paths
  changed_when: false

- name: global environment configuration | Find rust toolchain binary paths
  find:
    paths: "/home/{{ user.name }}/.rustup/toolchains/"
    recurse: no
    file_type: directory
  changed_when: false
  register: rust_toolchain_paths

- name: global environment configuration | Install shell path config file
  become: true
  template:
    dest: /etc/profile.d/paths.sh
    src: templates/paths.sh.j2
    mode: "u=rwx,g=rx,o=rx"

- name: global environment configuration | Install global ZSH configs sourcing /etc/profile
  become: true
  copy:
    dest: "{{ item }}"
    src: source_etc_profile
  with_items:
    - /etc/zsh/zprofile
    - /etc/zsh/zshrc
