# vim:ft=yaml.ansible:
---
- name: golang | Install packages
  package:
    state: present
    name:
      - go
      - goimports-reviser-bin
      - gopls
      - golangci-lint
      - staticcheck
  become: yes
