# vim:ft=yaml.ansible:
---
- name: golang | Install packages
  package:
    state: present
    name:
      - go
      - go-langserver-git
      - vim-gocode
  become: yes

- name: golang | Create gopath dirs
  file:
    path: "/home/{{ user.name }}/go/{{ item }}"
    state: directory
    owner: "{{ user.name }}"
  with_items:
    - src
    - bin
