# vim:ft=yaml.ansible:
---
- name: golang | Install packages
  package:
    state: present
    name:
      - go
      - gopls
      - golangci-lint
      - staticcheck
  become: yes

- name: golang | Create gopath dirs
  file:
    path: "/home/{{ user.name }}/go/{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  with_items:
    - src
    - bin
