# vim:ft=yaml.ansible:
---
- name: GPG | Install packages
  package:
    state: present
    name:
      - ccid
      - gnupg
      - imagemagick
      - pcsclite
      - qrencode
      - yubikey-manager
      - zbar
  become: true

- name: GPG | Create config dir
  file:
    path: "{{ user_home_dir }}/.gnupg"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0700
    state: directory

- name: GPG | Install config
  copy:
    dest: "{{ user_home_dir }}/.gnupg/gpg.conf"
    src: files/gpg.conf
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0600

- name: GPG | Install gpg-agent config
  copy:
    dest: "{{ user_home_dir }}/.gnupg/gpg-agent.conf"
    src: files/gpg-agent.conf
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0600

- name: GPG | Install scdaemon config
  copy:
    dest: "{{ user_home_dir }}/.gnupg/scdaemon.conf"
    src: files/scdaemon.conf
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0600

- name: GPG | Enable pcscd service
  become: true
  systemd:
    name: pcscd.service
    enabled: true
    state: started

- name: GPG | Find gpg-agent user service configs
  find:
    paths: "/usr/share/doc/gnupg/examples/systemd-user"
    excludes: "README"
    recurse: no
  changed_when: false
  register: gpg_agent_service_configs

- name: GPG | Install gpg-agent user service configs
  copy:
    dest: "{{ user_config_dir }}/systemd/user/{{ item.path | basename }}"
    src: "{{ item.path }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  with_items: "{{ gpg_agent_service_configs.files }}"

- name: GPG | Enable gpg-agent user services
  become: true
  become_user: "{{ user.name }}"
  systemd:
    enabled: true
    name: "{{ item.path | basename }}"
    scope: user
    daemon-reload: true
  with_items: "{{ gpg_agent_service_configs.files }}"
