# vim:ft=yaml.ansible:
---
- name: Grub | Install packages
  become: true
  package:
    state: present
    name:
      - efibootmgr
      - grub
      - intel-ucode
      - os-prober

- name: Grub | Run os-prober to find other OS
  command: os-prober
  become: true
  changed_when: false
  notify:
    - Regenerate grub.cfg

- name: Grub | Configure grub
  become: true
  notify:
    - Regenerate grub.cfg
  template:
    src: templates/grub.j2
    dest: /etc/default/grub

- name: Grub | Install grub
  when: bootstrap is defined and bootstrap == "true"
  notify:
    - Regenerate grub.cfg
  command: >
    grub-install --target=x86_64-efi
                 --efi-directory=/boot/efi
                 --bootloader-id=arch_grub
