# vim:ft=yaml.ansible:
---
- name: Grub Theme | Create theme directory
  become: true
  file:
    path: "{{ grub_theme_dir }}"
    state: directory
    mode: a+rw

- name: Grub Theme | Create icon directory
  file:
    path: "{{ grub_theme_dir }}/icons"
    state: directory

- name: Grub Theme | Install theme file
  tags: [base16]
  template:
    src: templates/grub-theme.txt.j2
    dest: "{{ grub_theme_dir }}/custom.txt"

# Grub theme assets sourced from https://github.com/vinceliuice/grub2-themes
# Grub theme guide http://wiki.rosalab.ru/en/index.php/Grub2_theme_tutorial
# Commands to generate Grub fonts defined near font vars

- name: Grub Theme | Install theme fonts
  become: true
  synchronize:
    src: assets/grub-theme/fonts/
    dest: "{{ grub_theme_dir }}"
    perms: false

- name: Grub Theme | Install theme selection assets
  become: true
  synchronize:
    src: assets/grub-theme/select/
    dest: "{{ grub_theme_dir }}"
    perms: false

- name: Grub Theme | Install theme icons
  become: true
  synchronize:
    src: assets/grub-theme/icons/
    dest: "{{ grub_theme_dir }}/icons"
    perms: false

- name: Grub Theme | Install theme wallpaper
  become: true
  synchronize:
    src: assets/wallpaper/
    dest: "{{ grub_theme_dir }}"
    perms: false
