# vim:ft=yaml.ansible:
---
- name: Launcher | Install packages
  package:
    state: present
    name:
      - rofi
      - rofi-pass
      - wofi
      - wofipassmenu
  become: true

- name: Launcher | Install rofi-toggle wrapper script
  copy:
    src: files/rofi-toggle
    dest: /usr/local/bin/rofi-toggle
    mode: a+x
  become: true

- name: Launcher | Install wofi-toggle wrapper script
  copy:
    src: files/wofi-toggle
    dest: /usr/local/bin/wofi-toggle
    mode: a+x
  become: true

- name: Launcher | Generate rofi base16 configs
  base16_builder:
    scheme: "{{ base16_scheme }}"
    scheme_family: "{{ base16_scheme_family }}"
    template: rofi
    schemes_source: "{{ base16['schemes_source'] }}"
    templates_source: "{{ base16['templates_source'] }}"
  register: base16_rofi
  tags: [base16]

- name: Launcher | Create rofi theme dir
  file:
    path: "{{ user_data_dir }}/rofi/themes"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: directory
  tags: [base16]

- name: Launcher | Create rofi config dir
  file:
    path: "{{ user_config_dir }}/rofi"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: directory
  tags: [base16]

- name: Launcher | Install rofi config
  template:
    src: "templates/rofi-config.j2"
    dest: "{{ user_config_dir }}/rofi/config"
  tags: [base16]

- name: Launcher | Install rofi theme
  template:
    src: "templates/rofi-theme.rasi.j2"
    dest: "{{ user_config_dir }}/rofi/theme.rasi"
  tags: [base16]

- name: Launcher | Create wofi config dir
  file:
    path: "{{ user_config_dir }}/wofi"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: directory
  tags: [base16]

- name: Launcher | Generate wofi base16 configs
  base16_builder:
    scheme: "{{ base16_scheme }}"
    scheme_family: "{{ base16_scheme_family }}"
    template: wofi
    schemes_source: "{{ base16['schemes_source'] }}"
    templates_source: "{{ base16['templates_source'] }}"
  register: base16_wofi
  tags: [base16]

- name: Launcher | Create wofi style.css
  copy:
    dest: "{{ user_config_dir }}/wofi/style.css"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    content: "{{ base16_wofi['schemes'][base16_scheme]['wofi']['themes']['base16-' + base16_scheme + '.css'] }}"
  tags: [base16]
