# vim:ft=yaml.ansible:
---
- name: Networking Pacakges | Install
  package:
    state: latest
    name:
      - dhclient
      - wireless_tools
      - wpa_supplicant
      - networkmanager
  become: true
