# vim:ft=yaml.ansible:
---
- name: Packaging | Update official packages
  pacman:
    update_cache: yes
    upgrade: yes
  retries: 2
  become: true

- name: Packaging | Install makepkg.conf
  template:
    src: templates/makepkg.conf.j2
    dest: "{{ user_home_dir }}/.makepkg.conf"

- name: Packaging | Check if yay is installed
  shell: which yay
  register: yay_installed
  failed_when: false
  changed_when: false

- name: Packaging | Clone yay-bin from AUR
  become: true
  become_user: "{{ user.name }}"
  git:
    repo: https://aur.archlinux.org/yay-bin.git
    dest: /tmp/yay-aur
  when: yay_installed.rc != 0

- name: Packaging | Build yay-bin
  become: true
  become_user: "{{ user.name }}"
  command: makepkg --noconfirm -f
  args:
    chdir: /tmp/yay-aur
  when: yay_installed.rc != 0

- name: Packaging | Install yay-bin
  become: true
  shell: pacman -U --noconfirm /tmp/yay-aur/yay-bin-*.pkg.tar.lzo
  when: yay_installed.rc != 0

- name: Packaging | Install pacman config
  become: true
  copy:
    src: files/pacman.conf
    dest: /etc/pacman.conf
