# vim:ft=yaml.ansible:
---
- name: Packaging | Update official packages
  pacman:
    update_cache: yes
    upgrade: yes
  retries: 2
  become: true

- name: Packaging | Install makepkg.conf
  template:
    src: templates/makepkg.conf.j2
    dest: "{{ user_home_dir }}/.makepkg.conf"

- name: Packaging | Check if yay is installed
  command: pacman -Qi yay
  register: yay_installed
  failed_when: false
  changed_when: false

- name: Packaging | Install yay build dependencies
  become: true
  package:
    state: present
    name: go
  when: yay_installed.rc != 0

- name: Packaging | Clone yay from AUR
  become: true
  become_user: "{{ yay_build_user | default(user.name) }}"
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/yay-aur
  retries: 3
  delay: 5
  when: yay_installed.rc != 0

- name: Packaging | Build yay
  become: true
  become_user: "{{ yay_build_user | default(user.name) }}"
  command: makepkg --noconfirm
  args:
    chdir: /tmp/yay-aur
  when: yay_installed.rc != 0

- name: Packaging | Install yay
  become: true
  shell: pacman -U --noconfirm /tmp/yay-aur/yay-*.pkg.tar.zst
  when: yay_installed.rc != 0

- name: Packaging | Install pacman config
  become: true
  copy:
    src: files/pacman.conf
    dest: /etc/pacman.conf
  when: not (iso_build | default(false))
