# vim:ft=yaml.ansible:
---
- name: Packaging | Update official packages
  pacman:
    update_cache: yes
    upgrade: yes
  retries: 2
  become: true

- name: Packaging | Install makepkg.conf
  template:
    src: templates/makepkg.conf.j2
    dest: "{{ user_home_dir }}/.makepkg.conf"

- name: Packaging | Install yay
  package:
    state: present
    name: yay
  become: true

- name: Packaging | Install pacman config
  become: true
  copy:
    src: files/pacman.conf
    dest: /etc/pacman.conf
