# vim:ft=yaml.ansible:
---
- name: power | Install packages
  package:
    state: present
    name:
      - ethtool
      - powerstat-git
      - powertop
      - thermald
      - tlp
      - tlp-rdw
  become: true

- name: power | Enable thermald
  service:
    name: thermald
    enabled: yes
    state: started
  become: true
  when: ansible_virtualization_role != "guest"

- name: power | Configure TLP
  copy:
    src: tlp
    dest: /etc/default/tlp
  become: true

- name: power | Enable TLP
  service:
    name: tlp
    enabled: yes
    state: started
  become: true

- name: power | Enable TLP Sleep
  service:
    name: tlp-sleep
    enabled: yes
  become: true

- name: power | Install logind config
  copy:
    src: files/logind.conf
    dest: /etc/systemd/logind.conf
  become: true

- name: power | Install systemd sleep config
  template:
    src: templates/systemd-sleep.conf.j2
    dest: /etc/systemd/sleep.conf
  become: true

- name: power | Replace systemctl suspend with suspend-then-hibernate
  file:
    src: /usr/lib/systemd/system/systemd-suspend-then-hibernate.service
    path: /etc/systemd/system/systemd-suspend.service
    force: true
    state: link
  become: true

- name: power | Create sysctl param directory
  become: true
  file:
    path: /etc/sysctl.d
    state: directory

- name: power | Configure sysctl params
  become: true
  copy:
    src: "{{ item }}"
    dest: "/etc/sysctl.d/{{ item | basename }}"
  with_fileglob:
    - files/sysctl.d/*

- name: power | Create udev rules directory
  become: true
  file:
    path: /etc/udev/rules.d
    state: directory

- name: power | Configure udev rules
  become: true
  copy:
    src: "{{ item }}"
    dest: "/etc/udev/rules.d/{{ item | basename }}"
  with_fileglob:
    - files/udev-rules.d/*
# Lock screen on suspend https://gist.github.com/raphiz/d69859645a9da08a0cf0778f42932120
# Enable wake on keypress
# Enable wake on mouse
