# vim:ft=yaml.ansible:
---
- name: power | Install packages
  package:
    state: present
    name:
      - ethtool
      - powerstat
      - powertop
      - thermald
      - tlp
  become: true

- name: power | Enable thermald
  service:
    name: thermald
    enabled: true
    state: started
    daemon_reload: true
  become: true
  when: ansible_virtualization_role != "guest"

- name: power | Configure TLP
  copy:
    src: tlp
    dest: /etc/default/tlp
  become: true

- name: power | Enable TLP
  systemd:
    name: tlp
    enabled: true
    state: started
    daemon-reload: true
  become: true

- name: power | Install service to disable wake-up from spurious USB3 signals
  copy:
    src: files/disable-xhc-wakeup.service
    dest: /etc/systemd/system/disable-xhc-wakeup.service
  become: true

- name: power | Enable service to disable wake-up from spurious USB3 signals
  systemd:
    name: disable-xhc-wakeup.service
    enabled: true
    daemon-reload: true
  become: true

- name: power | Install logind config
  copy:
    src: files/logind.conf
    dest: /etc/systemd/logind.conf
  become: true

- name: power | Install systemd sleep config
  template:
    src: templates/systemd-sleep.conf.j2
    dest: /etc/systemd/sleep.conf
  become: true

- name: power | Replace systemctl suspend with suspend-then-hibernate
  file:
    src: /usr/lib/systemd/system/systemd-suspend-then-hibernate.service
    path: /etc/systemd/system/systemd-suspend.service
    force: true
    state: link
  become: true

# Async power management appears to be causing lock ups during suspend and resume
- name: power | Disable async suspend and resume
  copy:
    src: files/disable-pm-async.service
    dest: /etc/systemd/system/disable-pm-async.service
  become: true

- name: power | Enable service that disables async suspend and resume
  service:
    name: disable-pm-async.service
    enabled: true
    state: started
    daemon_reload: true
  become: true

- name: power | Create sysctl param directory
  become: true
  file:
    path: /etc/sysctl.d
    state: directory

- name: power | Configure sysctl params
  become: true
  copy:
    src: "{{ item }}"
    dest: "/etc/sysctl.d/{{ item | basename }}"
  with_fileglob:
    - files/sysctl.d/*

- name: power | Create udev rules directory
  become: true
  file:
    path: /etc/udev/rules.d
    state: directory

- name: power | Configure udev rules
  become: true
  copy:
    src: "{{ item }}"
    dest: "/etc/udev/rules.d/{{ item | basename }}"
  with_fileglob:
    - files/udev-rules.d/*

- name: power | Enable audio codec power management
  become: true
  notify:
    - Regenerate mkinitcpio ramdisk
  copy:
    content: "options snd_hda_intel power_save=1 power_save_controller=Y"
    dest: "/etc/modprobe.d/audio_powersave.conf"
