# vim:ft=yaml.ansible:
---
- name: python | Install pip
  package:
    state: present
    name:
      - ruff
      - pyright
      - python-pip
      - python-pylint
      - python-poetry
  become: true
