# vim:ft=yaml.ansible:
---
- name: python | Install pip
  package:
    state: present
    name:
      - python-pip
      - python-pipenv
      - python-black-git
      - python-language-server
  become: true
