# vim:ft=yaml.ansible:
---
- name: qemu guest| Blacklist coretemp module
  become: true
  notify:
    - Regenerate mkinitcpio ramdisk
  copy:
    content: "blacklist coretemp"
    dest: "/etc/modprobe.d/blacklist_coretemp.conf"
