# vim:ft=yaml.ansible:
---
- name: qemu guest | Blacklist coretemp module
  become: true
  notify:
    - Regenerate mkinitcpio ramdisk
  copy:
    content: "blacklist coretemp"
    dest: "/etc/modprobe.d/blacklist_coretemp.conf"

- name: qemu guest | Install guest agent package
  package:
    state: present
    name: qemu-guest-agent
  become: true

- name: qemu guest | Enable qemu guest agent service
  service:
    name: qemu-ga.service
    enabled: yes
    state: started
    daemon-reload: true
  become: true
