# vim:ft=yaml.ansible:
---
- name: Qt | Create config dirs
  file:
    path: "{{ user_config_dir }}/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: directory
  with_items:
    - qt5ct
    - qt5ct/colors
  tags: [base16]

# Provides desktop styling info to Qt5 apps
- name: Qt | Install packages
  package:
    state: present
    name:
      - qt5ct
      - qt5-wayland
      - qt6-wayland
  become: true

- name: Qt | Generate base16 configs
  base16_builder:
    scheme: "{{ base16_scheme }}"
    scheme_family: "{{ base16_scheme_family }}"
    template: qt5ct
    schemes_source: "{{ base16['schemes_source'] }}"
    templates_source: "{{ base16['templates_source'] }}"
  register: base16_qt5ct
  tags: [base16]

- name: Qt | Install qt5ct config
  copy:
    content: "{{ base16_qt5ct['schemes'][base16_scheme]['qt5ct']['qt5ct_appearance_conf']['base16-' + base16_scheme + '.conf'] }}"
    dest: "{{ user_config_dir }}/qt5ct/qt5ct.conf"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  tags: [base16]

- name: Qt | Install qt5ct colors
  copy:
    content: "{{ base16_qt5ct['schemes'][base16_scheme]['qt5ct']['colors']['base16-' + base16_scheme + '.conf'] }}"
    dest: "{{ user_config_dir }}/qt5ct/colors/base16-{{ base16_scheme }}.conf"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  tags: [base16]
