# vim:ft=yaml.ansible:
---
- name: Ruby | Install packages
  package:
    state: present
    name:
      - ruby-irb
      - ruby-bundler
      - ruby-rubocop
      - ruby-solargraph
  become: true

- name: Ruby | Install global gemrc
  become: true
  copy:
    src: files/gemrc
    dest: /etc/gemrc

- name: Ruby | Install irb config
  copy:
    src: files/irbrc
    dest: "/home/{{ user.name }}/.irbrc"
    owner: "{{ user.name }}"

- name: Ruby | Install rubocop config
  become: true
  copy:
    src: files/rubocop.yml
    dest: "/home/{{ user.name }}/.rubocop.yml"
    owner: "{{ user.name }}"
