# vim:ft=yaml.ansible:
---
- name: Rust | Install packages
  package:
    name:
      - rustup
      - rust-racer
      - rust-analyzer
  become: true

- name: Rust | Install rust nightly
  command: rustup default nightly
  args:
    creates: "/home/{{ user.name }}/.rustup/toolchains/stable-x86_64-unknown-linux-gnu"

- name: Rust | Install rls
  command: rustup component add rls rust-analysis rust-src
  args:
    creates: "/home/{{ user.name }}/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rls"

- name: Rust | Install rustfmt
  command: rustup component add rustfmt
  args:
    creates: "/home/{{ user.name }}/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustfmt"
