# vim:ft=yaml.ansible:
---
- name: Rust | Install rustup
  package:
    name: rustup
    state: present
  become: true

- name: Rust | Install rust stable
  command: rustup default stable
  args:
    creates: "/home/{{ user.name }}/.rustup/toolchains/stable-x86_64-unknown-linux-gnu"

- name: Rust | Install rls
  command: rustup component add rls-preview rust-analysis rust-src
  args:
    creates: "/home/{{ user.name }}/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rls"

- name: Rust | Install rustfmt
  command: rustup component add rustfmt-preview
  args:
    creates: "/home/{{ user.name }}/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustfmt"

- name: Rust | Install racer
  package:
    name: rust-racer
    state: present
  become: true
