# vim:ft=yaml.ansible:
---
- name: Secrets | Install packages
  become: true
  package:
    state: present
    name:
      - pass
      - browserpass
      - browserpass-firefox
      - yubikey-manager
      - pcsclite
      - ccid

- name: Secrets | Enable pcscd service for smart cards
  service:
    name: pcscd.service
    enabled: true
    state: started
    daemon-reload: true
  become: true

- name: Secrets | Install scripts
  copy:
    src: "files/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: a+x
  become: true
  with_items:
    - generate-primary-gpg-key
    - configure-yubikey

- name: Secrets | Clone password-store
  git:
    repo: git@gitlab.com:mnussbaum/password-store.git
    version: master
    dest: "{{ user_data_dir }}/password-store"
    accept_hostkey: true
    update: false

# This is just so that I don't need to manually configure browserpass to use
# the XDG_DATA_HOME password-store
- name: Secrets | Symlink password-store from data directory to default location
  file:
    src: "{{ user_data_dir }}/password-store"
    dest: "/home/{{ user.name }}/.password-store"
    state: link
