# vim:ft=yaml.ansible:
---
- name: Secrets | Install packages
  become: true
  package:
    state: present
    name:
      - pass
      - browserpass
      - browserpass-firefox

- name: Clone password-store
  git:
    repo: git@gitlab.com:mnussbaum/password-store.git
    version: master
    dest: "{{ user_data_dir }}/password-store"
    accept_hostkey: yes

# This is just so that I don't need to manually configure browserpass to use
# the XDG_DATA_HOME password-store
- file:
    src: "{{ user_data_dir }}/password-store"
    dest: "/home/{{ user.name }}/.password-store"
    state: link
