# vim:ft=yaml.ansible:
---
- name: Secrets | Install packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - pass
    - browserpass
    - firefox-browserpass

- name: Secrets | Install Firefox Firejail profile to grant password-store access
  become: true
  copy:
    src: files/firejail-firefox-common.local
    dest: /etc/firejail/firefox-common.local

- name: Clone password-store
  git:
    repo: git@gitlab.com:mnussbaum/password-store.git
    version: master
    dest: "/home/{{ user.name }}/.local/share/password-store"
    accept_hostkey: yes

# This is just so that I don't need to manually configure browserpass to use
# the XDG_DATA_HOME password-store
- file:
    src:  "/home/{{ user.name }}/.local/share/password-store"
    dest: "/home/{{ user.name }}/.password-store"
    state: link
