# vim:ft=yaml.ansible:
---
- name: Appearance facts | Set night appearance
  when: appearance is undefined or appearance == "night"
  set_fact:
    base16_scheme: "{{ base16['night_scheme'] }}"
    base16_scheme_family: "{{ base16['night_scheme_family'] }}"
    desktop_background: "{{ user_data_dir }}/wallpapers/night.jpg"

- name: Appearance facts | Set daytime appearance
  when: appearance is defined and appearance == "daytime"
  set_fact:
    base16_scheme: "{{ base16['day_scheme'] }}"
    base16_scheme_family: "{{ base16['day_scheme_family'] }}"
    desktop_background: "{{ user_data_dir }}/wallpapers/daytime.jpg"
