# vim:ft=yaml.ansible:
---
- name: SSH | Create config dir
  file:
    path: "{{ user_home_dir }}/.ssh"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: directory

- name: SSH | Install config
  copy:
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    src: files/ssh-config
    dest: "{{ user_home_dir }}/.ssh/config"


