# vim:ft=yaml.ansible:
---
- name: networking | Configure nameservers
  copy:
    src: files/resolvconf.conf
    dest: /etc/resolvconf.conf
  become: true

- name: networking | Configure NetworkManager
  copy:
    src: files/NetworkManager.conf
    dest: /etc/NetworkManager/NetworkManager.conf
  become: true

- name: networking | Disable dhcpcd
  service:
    name: dhcpcd
    enabled: no
    state: stopped
  become: true

- name: networking | Enable wpa_supplicant
  service:
    name: wpa_supplicant
    enabled: yes
    state: started
  become: true

- name: networking | Enable NetworkManager
  service:
    name: NetworkManager
    enabled: yes
    state: started
  become: true

# Do I need to start the dispatcher? If so, should it set remain after exit?
- name: networking | Enable NetworkManager dispatcher
  service:
    name: NetworkManager-dispatcher
    enabled: yes
    state: started
  become: true
