# vim:ft=yaml.ansible:
---
- name: Swap | Get power_image size
  command: cat /sys/power/image_size
  register: power_image_size_bytes
  changed_when: false

- name: Swap | Create /etc/sysctl.conf
  become: true
  copy:
    content: ""
    dest: /etc/sysctl.conf
    force: no
    mode: 0600

# TODO: Set vmf cache pressure to 1 to improve perf
- name: Swap | Configure swapfile
  include_role:
    name: geerlingguy.swap
    apply:
      become: true
  vars:
    ansible_become: true
    swap_file_path: /swapfile
    swap_file_size_mb: "{{ ((power_image_size_bytes.stdout | int) / (1024**2)) | int }}"
    swap_swappiness: "1"

- name: Swap | Get swapfile offset
  shell: filefrag -v /swapfile | awk '{gsub(/\./,""); if($1=="0:"){print $4}}'
  register: swapfile_offset
  changed_when: false
  become: true
