# vim:ft=yaml.ansible:
---
- name: sway | Create config dirs
  file:
    path: "{{ user_config_dir }}/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: directory
  with_items:
    - mako
    - sway
    - swaylock
  tags: [base16]

- name: sway | Install sway env file
  become: true
  copy:
    src: files/sway-env
    dest: "{{ user_config_dir }}/sway/env"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: sway | Install sway packages
  package:
    state: present
    name:
      - mesa
      - wlroots
      - sway
      - swaybg
      - swayidle
      - swaylock-effects-git
      - libnotify
      - mako
      - wl-clipboard-git
      - glfw-wayland  # Provides libs for GLFW apps
      - grim-git
      - slurp
      - satty-git
      - xorg-xwayland
      - dbus-broker-launch
      - wdisplays
  become: true

- name: sway | Generate base16 configs
  base16_builder:
    scheme: "{{ base16_scheme }}"
    scheme_family: "{{ base16_scheme_family }}"
    template: i3
    schemes_source: "{{ base16['schemes_source'] }}"
    templates_source: "{{ base16['templates_source'] }}"
  register: base16_i3
  tags: [base16]

- name: sway | Install config
  template:
    src: templates/sway_config.j2
    dest: "{{ user_config_dir }}/sway/config"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  tags: [base16]
  with_items:
    - sway

- name: sway | Install swaylock config
  template:
    src: templates/swaylock_config.j2
    dest: "{{ user_config_dir }}/swaylock/config"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  tags: [base16]
  with_items:
    - sway

- name: sway | Generate mako base16 config
  base16_builder:
    scheme: "{{ base16_scheme }}"
    scheme_family: "{{ base16_scheme_family }}"
    template: mako
    schemes_source: "{{ base16['schemes_source'] }}"
    templates_source: "{{ base16['templates_source'] }}"
  register: base16_mako
  tags: [base16]

- name: sway | Write mako config to a file
  template:
    src: templates/mako.j2
    dest: "{{ user_config_dir }}/mako/config"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  tags: [base16]

- name: Sway | Install services
  copy:
    src: "files/{{ item }}"
    dest: "{{ user_config_dir }}/systemd/user/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  with_items:
    - sway-session.target
    - sway.service

- name: Sway | Install swayidle service
  template:
    src: templates/swayidle.service.j2
    dest: "{{ user_config_dir }}/systemd/user/swayidle.service"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: Sway | Enable swayidle
  become: true
  become_user: "{{ user.name }}"
  systemd:
    enabled: true
    name: swayidle.service
    scope: user
    daemon-reload: true
