# vim:ft=yaml.ansible:
---
- name: sway | Install Wayland env file
  become: true
  copy:
    src: files/wayland-env
    dest: /etc/wayland-env

- name: sway | Create config dir
  file:
    path: "/home/{{ user.name }}/.config/sway"
    owner: "{{ user.name }}"
    state: directory

- name: sway | Install sway packages
  package:
    state: present
    name:
      - wlroots-git
      - sway-git
      - swayidle-git
      - swaylock-git
      - grim-git
      - slurp-git
      - wl-clipboard-git
  become: true

- name: sway | Generate base16 configs
  base16_builder:
    scheme: "{{ base16_scheme }}"
    scheme_family: "{{ base16_scheme_family }}"
    template: i3
    schemes_source: "{{ base16_schemes_source }}"
    templates_source: "{{ base16_templates_source }}"
  register: base16_i3
  tags: [base16]

- name: sway | Install config
  template:
    src: templates/sway_and_i3_config.j2
    dest: "/home/{{ user.name }}/.config/sway/config"
    owner: "{{ user.name }}"
  tags: [base16]
  with_items:
    - sway

- name: Sway | Install services
  copy:
    src: "files/{{ item }}"
    dest: "/home/{{ user.name }}/.config/systemd/user/{{ item }}"
    owner: "{{ user.name }}"
  with_items:
    - sway.service
    - swayidle.service

- name: Sway | Enable services
  become: true
  become_user: "{{ user.name }}"
  systemd:
    enabled: true
    name: "{{ item }}"
    scope: user
    daemon-reload: true
  with_items:
    - sway.service
    - swayidle.service
