# vim:ft=yaml.ansible:
---
- name: Tablet mode | Install packages
  package:
    state: present
    name:
      - rot8-git
      - virtboard-git

- name: Tablet mode | Install systemd services
  copy:
    src: "files/{{ item }}.service"
    dest: "{{ user_config_dir }}/systemd/user/{{ item }}.service"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  with_items:
    - rot8
    - virtboard

- name: Tablet mode | Install toggle module scripts
  copy:
    src: "files/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: a+x
  become: true
  with_items:
    - rot8-rotation-lock-status
    - toggle-rot8
    - virtboard-open-status
    - toggle-virtboard
