# vim:ft=yaml.ansible:
---
- name: Tablet mode | Install packages
  package:
    state: present
    name: rot8-git

- name: Tablet mode | Install systemd service
  copy:
    src: "files/rot8.service"
    dest: "{{ user_config_dir }}/systemd/user/rot8.service"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: Tablet mode | Install toggle module scripts
  copy:
    src: "files/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: a+x
  become: true
  with_items:
    - rot8-rotation-lock-status
    - toggle-rot8
