# vim:ft=yaml.ansible:
---
- name: termite | Install termite
  package:
    name: termite
    state: present
  become: true

- name: termite | Create config dir
  file:
    path: "/home/{{ user.name }}/.config/termite"
    owner: "{{ user.name }}"
    state: directory

- name: termite | Install config
  template:
    src: templates/termite_config.j2
    dest: "/home/{{ user.name }}/.config/termite/config"
    owner: "{{ user.name }}"
