# vim:ft=yaml.ansible:
---
- name: user | Create wheel group
  become: true
  group: name=wheel state=present

- name: user | Configure sudoers
  become: true
  lineinfile:
    dest: /etc/sudoers.d/ansible
    line: "%wheel ALL=(ALL) ALL"
    state: present
    create: yes
    validate: "/usr/bin/visudo -cf %s"

- name: user | Check if user exists
  command: "getent passwd {{ user.name }}"
  register: check_if_user_exists
  ignore_errors: true
  changed_when: false

- name: user | Prompt for user password to create
  pause:
    prompt: "Enter desired user password"
    echo: false
  when: check_if_user_exists is failed
  register: user_password
  no_log: true

- name: user | Create individual user group
  become: true
  group:
    name: "{{ user.group }}"
    state: present

- name: user | Create user
  become: true
  user:
    name: "{{ user.name }}"
    group: "{{ user.group }}"
    groups:
      - "{{ user.group }}"
      - input
      - wheel
    password: "{{ user_password.user_input | default('password') | password_hash('sha512') }}"
    shell: "{{ user.shell }}"
    update_password: on_create
    append: true

- name: user | Create data dir
  file:
    path: "{{ user_data_dir }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: directory

- name: user | Create user config dir
  file:
    path: "{{ user_config_dir }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: directory

- name: user | Create user source code dir
  file:
    path: "/home/{{ user.name }}/src"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: directory

- name: user | Create user systemd dir
  file:
    path: "{{ user_config_dir }}/systemd/user"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: directory
