# vim:ft=yaml.ansible:
---
- name: Wallpaper | Create directory
  become: true
  file:
    path: "{{ wallpaper.desktop_dir }}"
    state: directory

- name: Wallpaper | Install desktop background images
  become: true
  copy:
    src: "{{ item }}"
    dest: "{{ wallpaper.desktop_dir }}/{{ item | basename }}"
  with_fileglob:
    - assets/wallpaper/*
