# vim:ft=yaml.ansible:
---
- name: Wallpaper | Create directory
  become: true
  file:
    path: "{{ wallpaper_dir }}"
    state: directory

- name: Wallpaper | Download daytime wallpaper image
  become: true
  copy:
    src: assets/lost_coast_golden_path.jpg
    dest: "{{ wallpaper_dir }}/lost_coast_golden_path.jpg"

- name: Wallpaper | Symlink daytime wallpaper in place
  become: true
  file:
    src: "{{ wallpaper_dir }}/lost_coast_golden_path.jpg"
    path: "{{ wallpaper_dir }}/daytime.jpg"
    force: true
    state: link

- name: Wallpaper | Download night wallpaper image
  become: true
  copy:
    src: assets/evening_train.jpg
    dest: "{{ wallpaper_dir }}/evening_train.jpg"

- name: Wallpaper | Symlink night wallpaper in place
  become: true
  file:
    src: "{{ wallpaper_dir }}/evening_train.jpg"
    path: "{{ wallpaper_dir }}/night.jpg"
    force: true
    state: link
