# vim:ft=yaml.ansible:
---
- name: Waybar | Install package
  package:
    name: waybar-git
    state: present
  become: true

- name: Waybar | Install waybar wrapper script
  copy:
    src: files/waybar-wrapper
    dest: /usr/local/bin/waybar-wrapper
    mode: a+x
  become: true

- name: Waybar | Create waybar config dir
  file:
    path: "/home/{{ user.name }}/.config/waybar"
    owner: "{{ user.name }}"
    state: directory

- name: Waybar | Install waybar config
  template:
    src: templates/waybar-config.json.j2
    dest: "/home/{{ user.name }}/.config/waybar/config"

- name: Waybar | Install waybar styling
  template:
    src: templates/waybar-style.css.j2
    dest: "/home/{{ user.name }}/.config/waybar/style.css"
  tags: [base16]

- name: Install waybar-sway-workspace-output-manager
  command: cargo install --git=https://github.com/mnussbaum/waybar-sway-workspace-output-manager
  args:
    creates: "/home/{{ user.name }}/.cargo/bin/waybar-sway-workspace-output-manager"

- name: Waybar | Create waybar-sway-workspace-output-manager config dir
  file:
    path: "/home/{{ user.name }}/.config/waybar-sway-workspace-output-manager"
    owner: "{{ user.name }}"
    state: directory

- name: Waybar | Install waybar-sway-workspace-output-manager config file
  template:
    src: templates/waybar-sway-workspace-output-manager-config.j2
    dest: "/home/{{ user.name }}/.config/waybar-sway-workspace-output-manager/config"
  tags: [base16]

# Top left, workspaces. Terminal and browser assigned, rest numbered
# Top right, laptop status. Battery, failing systemd unit count, memory, cpu, wifi, time
# Bottom bar only show on hover
# Bottom left, notifications. Email count, SMS count, maybe tray?
# Bottom right, real world info. Weather, music, volume, maybe displays?
