# vim:ft=yaml.ansible:
---
# TODO: Make waybars reveal over full screen when screen is touched or mouse is moved

- name: Waybar | Install package
  package:
    name: waybar-git
    state: present
  become: true

- name: Waybar | Create waybar config dir
  file:
    path: "{{ user_config_dir }}/waybar"
    group: "{{ user.group }}"
    owner: "{{ user.name }}"
    state: directory

- name: Waybar | Install waybar config
  template:
    src: templates/waybar-config.json.j2
    dest: "{{ user_config_dir }}/waybar/config"
  tags: [base16]

- name: Waybar | Install waybar styling
  template:
    src: templates/waybar-style.css.j2
    dest: "{{ user_config_dir }}/waybar/style.css"
  tags: [base16]

- name: Waybar | Install service
  copy:
    src: files/waybar.service
    dest: "{{ user_config_dir }}/systemd/user/waybar.service"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: Waybar | Enable service
  become: true
  become_user: "{{ user.name }}"
  systemd:
    enabled: true
    name: waybar.service
    scope: user
    daemon-reload: true

- name: Install waybar-sway-workspace-output-manager
  command: cargo install --git=https://github.com/mnussbaum/waybar-sway-workspace-output-manager
  args:
    creates: "/home/{{ user.name }}/.cargo/bin/waybar-sway-workspace-output-manager"

- name: Waybar | Create waybar-sway-workspace-output-manager config dir
  file:
    path: "{{ user_config_dir }}/waybar-sway-workspace-output-manager"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: directory

- name: Waybar | Install waybar-sway-workspace-output-manager config file
  template:
    src: templates/waybar-sway-workspace-output-manager-config.j2
    dest: "{{ user_config_dir }}/waybar-sway-workspace-output-manager/config"
  tags: [base16]

# Goal:
# Top left, workspaces. Terminal and browser assigned, rest numbered
# Top right, laptop status. Battery, failing systemd unit count, hw temp, memory, cpu, wifi, time
# Bottom left, toggles. Screen lock, idle lock, virtual keyboard toggle
# Bottom right, real world info. Weather, music, sms?

- name: Waybar | Install waybar-sway-workspace-output-manager service
  copy:
    src: files/waybar-sway-workspace-output-manager.service
    dest: "{{ user_config_dir }}/systemd/user/waybar-sway-workspace-output-manager.service"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: Waybar | Enable waybar-sway-workspace-output-manager service
  become: true
  become_user: "{{ user.name }}"
  systemd:
    enabled: true
    name: waybar-sway-workspace-output-manager.service
    scope: user
    daemon-reload: true
