# vim:ft=yaml.ansible:
---
- name: Xorg | Install packages
  package:
    state: present
    name:
      - mesa
      - vulkan-intel
      - xorg-server
      - xorg-xdpyinfo
      - xorg-xinput
      - xorg-xrdb
  become: true

- name: Xorg | Configure xorg to run with root privileges
  copy:
    dest: /etc/X11/Xwrapper.config
    src: Xwrapper.config
  become: true

- name: Xorg | Make xorg config dir
  become: true
  file:
    path: /etc/X11/xorg.conf.d
    state: directory

- name: Xorg | Generate base16 configs
  base16_builder:
    scheme: "{{ base16_scheme }}"
    scheme_family: "{{ base16_scheme_family }}"
    template: xresources
    schemes_source: "{{ base16_schemes_source }}"
    templates_source: "{{ base16_templates_source }}"
  register: base16_xresources
  tags: [base16]

- name: Xorg | Install Xresources
  template:
    src: templates/Xresources.j2
    dest: "/home/{{ user.name }}/.Xresources"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  tags: [base16]

- name: Xorg | Install templated services
  template:
    src: "templates/{{ item }}.j2"
    dest: "{{ user_config_dir }}/systemd/user/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  with_items:
    - xorg.service

- name: Xorg | Install services
  copy:
    src: "files/{{ item }}"
    dest: "{{ user_config_dir }}/systemd/user/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  with_items:
    - xrdb.service

- name: Xorg | Enable systemd servicea
  become: true
  become_user: "{{ user.name }}"
  systemd:
    enabled: true
    name: "{{ item }}"
    scope: user
    daemon-reload: true
  with_items:
    - xorg.service
    - xrdb.service
