# vim:ft=yaml.ansible:
---
- name: zathura | Install packages
  package:
    state: present
    name:
      - zathura
      - zathura-pdf-poppler
      # - zathura-epub-git broken as of 1/28/18
  become: true

- name: zathura | Create config dir
  file:
    path: "/home/{{ user.name }}/.config/zathura"
    owner: "{{ user.name }}"
    state: directory

- name: zathura | Generate base16 configs
  base16_builder:
    scheme: "{{ base16_scheme }}"
    scheme_family: "{{ base16_scheme_family }}"
    template: zathura
    schemes_source: "{{ base16_schemes_source }}"
    templates_source: "{{ base16_templates_source }}"
  register: base16_zathura
  tags: [base16]

- name: zathura | Install config
  template:
    src: templates/zathurarc.j2
    dest: "/home/{{ user.name }}/.config/zathura/zathurarc"
  tags: [base16]
