# vim:ft=yaml.ansible:
---
- name: ZSH | Install package
  package:
    state: present
    name:
      - zsh
      - zsh-syntax-highlighting
      - python-pystache # For base16_builder
      - spaceship-prompt-git
  become: true

- name: ZSH | Install dircolors config
  copy:
    dest: "{{ user_config_dir }}/dircolors"
    src: dircolors
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: ZSH | Install zshrc
  copy:
    dest: "/home/{{ user.name }}/.zshrc"
    src: zshrc
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: ZSH | Create zsh config dir
  file:
    path: "{{ user_config_dir }}/zsh"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: directory

- name: ZSH | Generate base16 configs
  base16_builder:
    scheme: "{{ base16_scheme }}"
    scheme_family: "{{ base16_scheme_family }}"
    template: shell
    schemes_source: "{{ base16['schemes_source'] }}"
    templates_source: "{{ base16['templates_source'] }}"
  register: base16_shell
  tags: [base16]

- name: ZSH | Install base16 zsh config
  copy:
    dest: "{{ user_config_dir }}/zsh/00-base16.zsh"
    content: "{{ base16_shell['schemes'][base16_scheme]['shell']['scripts']['base16-' + base16_scheme + '.sh'] }}"
  tags: [base16]

- name: ZSH | Install zsh configs
  copy:
    dest: "{{ user_config_dir }}/zsh/{{ item | basename }}"
    src: "{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  with_fileglob:
    - files/zsh-configs/*
