# vim:ft=yaml.ansible:
---
- name: Install packages
  package:
    state: present
    name:
      - bluez
      - bluez-tools
      - bluez-utils

- name: Power on afer reboot
  lineinfile:
    dest: /etc/bluetooth/main.conf
    regexp: ".*AutoEnable.*"
    line: "AutoEnable=true"

- name: Always be discoverable
  lineinfile:
    dest: /etc/bluetooth/main.conf
    regexp: ".*DiscoverableTimeout.*"
    line: "DiscoverableTimeout=0"

- name: Enable service
  systemd:
    enabled: true
    name: bluetooth
# To add a bluetooth device:
# bluetoothctl
# power on
# agent on
# default-agent
# scan on
# pair <MAC address>
# connect <MAC address>
# trust <MAC address>
