#!/usr/bin/env python


def main():
    # TODO: Find a new source of sunset timing that isn't clight

    # clight_call_result = subprocess.run(
    #     [
    #         "busctl",
    #         "--user",
    #         "get-property",
    #         "org.clight.clight",
    #         "/org/clight/clight",
    #         "org.clight.clight",
    #         "DayTime",
    #     ],
    #     check=True,
    #     capture_output=True,
    #     encoding="utf-8",
    # )
    #
    # # Output will be "i 1" for day time, "i 0" for night
    # period_match = re.search(r"i ([01])", clight_call_result.stdout)
    # if period_match is None:
    #     raise RuntimeError(
    #         "No day/night info found in clight dbus output: {}".format(
    #             clight_call_result.stdout
    #         )
    #     )
    #
    # if bool(int(period_match.group(1))):
    #     print("night", end="")
    # else:
    #     print("daytime", end="")
    print("daytime", end="")

    return


if __name__ == "__main__":
    main()
