---
user:
  name: mnussbaum
  group: mnussbaum
  shell: /usr/bin/zsh
  email: michaelnussbaum08@gmail.com
  password: "{{ user_password }}"

font:
  sans_family: "NotoSans Nerd Font"
  serif_family: "NotoSerif Nerd Font"
  monospace_family: "FuraMono Nerd Font Mono"
  size: 20
  rofi_size: 10
  grub_graphical_size: 50

idle_thresholds:
  lock_screen_delay_minutes: 5
  suspend_delay_minutes: 10
  hibernate_delay_minutes: 45

base16:
  day_scheme: gruvbox-dark-hard
  day_scheme_family: gruvbox
  night_scheme: unikitty-dark
  night_scheme_family: unikitty
  schemes_source: "https://github.com/mnussbaum/base16-schemes-source"
  templates_source: "https://github.com/mnussbaum/base16-templates-source"

grub_theme_dir: /boot/grub/themes/custom

wallpaper:
  desktop_dir: /usr/share/backgrounds
  daytime_image: lost_coast_golden_path.jpg
  night_image: merch-mart.png
