# vim:ft=yaml.ansible:
---
- name: Install packages
  package:
    state: present
    name:
      - libinput
      - libinput-tools
      - libinput-gestures
      - wtype

- name: Install libinput-gestures service
  copy:
    dest: /etc/systemd/user/libinput-gestures.service
    src: libinput-gestures.service

- name: Install libinput-gestures.conf
  copy:
    dest: /etc/libinput-gestures.conf
    src: libinput-gestures.conf

- name: Install systemd user preset
  template:
    src: 80-libinput.preset.j2
    dest: /usr/lib/systemd/user-preset/80-libinput.preset

