# vim:ft=yaml.ansible:
---
- name: Install packages
  package:
    state: present
    name:
      - libinput
      - libinput-tools
      - libinput-gestures
      - wtype

- name: Install libinput-gestures service
  copy:
    dest: /etc/systemd/user/libinput-gestures.service
    src: libinput-gestures.service

- name: Install libinput-gestures.conf
  copy:
    dest: /etc/libinput-gestures.conf
    src: libinput-gestures.conf

- name: Enable libinput-gestures service
  when: optional_daemons.libinput_gestures
  systemd:
    enabled: true
    name: libinput-gestures.service
    scope: global
    daemon-reload: "{{ svc_daemon_reload }}"
