# vim:ft=yaml.ansible:
---
- name: Install themes
  package:
    state: present
    name:
      - gnome-themes-extra

- name: Create config dir
  file:
    path: /etc/gtk-3.0
    state: directory

- name: Install config
  template:
    src: gtk_3_0_settings.ini.j2
    dest: /etc/gtk-3.0/settings.ini
