# vim:ft=yaml.ansible:
---
- name: Create wheel group
  group: name=wheel state=present

- name: Create skel .zshrc to suppress zsh-newuser-install
  copy:
    content: ""
    dest: /etc/skel/.zshrc
    force: false

- name: Create skel Projects dir
  file:
    path: /etc/skel/Projects
    state: directory

- name: Create skel .local/share dir
  file:
    path: /etc/skel/.local/share
    state: directory
