# vim:ft=yaml.ansible:
---
- name: Download delta themes
  get_url:
    url: https://raw.githubusercontent.com/dandavison/delta/master/themes.gitconfig
    dest: /usr/share/delta-themes.gitconfig

- name: Install delta diff tool
  package:
    name:
      - git-delta
      - mergiraf
    state: present

- name: Install gitconfig
  template:
    src: gitconfig.j2
    dest: /etc/gitconfig

- name: Create gitconfig.d dir
  file:
    path: /etc/gitconfig.d
    state: directory

- name: Install personal gitconfig
  template:
    src: personal-gitconfig.j2
    dest: /etc/gitconfig.d/personal

- name: Install eeek gitconfig
  copy:
    src: eeek-gitconfig
    dest: /etc/gitconfig.d/eeek

- name: Install attributes file for mergiraf
  copy:
    src: gitattributes
    dest: /etc/gitconfig.d/attributes
