# vim: ft=dosini

[Config]
PassEnvironment=ANSIBLE_EXTRA_ARGS SKIP_POSTINST

[Distribution]
Distribution=arch

[Validation]
Passphrase=~/.cache/mkosi-luks-bootstrap.passphrase

[Build]
WithNetwork=yes
Incremental=yes
BuildSources=
    ../
    ~/.local/share/password-store:password-store
    ~/.cache/yay/yay-bin:yay-pkg
    ~/.cargo/registry:cargo-registry
    ~/.cache/sccache:sccache-cache

CacheDirectory=~/.cache/mkosi
PackageCacheDirectory=~/.cache/mkosi/pacman-pkg
BuildDirectory=~/.cache/mkosi/build
BuildSourcesEphemeral=buildcache
UseSubvolumes=auto

[Output]
Format=disk
Output=arch
ImageVersion=a
SplitArtifacts=partitions,uki

[Content]
KernelCommandLine=rw quiet
BuildScripts=../mkosi.build
BuildPackages=rust
    sccache
PostInstallationScripts=../mkosi.postinst.chroot
FinalizeScripts=../mkosi.finalize
Bootable=yes
Timezone=US/Pacific
Locale=en_US.UTF-8
CleanPackageMetadata=false
ExtraTrees=
    ..:/usr/local/share/arch-ansible
    ~/.local/share/password-store:/usr/local/share/password-store
    /etc/pacman.d/mirrorlist:/etc/pacman.d/mirrorlist
    ~/.cache/mkosi-luks-bootstrap.passphrase:/efi/loader/credentials/luks.passphrase
    ~/.cache/mkosi-luks-bootstrap.passphrase:/etc/cryptsetup-keys.d/luks.passphrase
    ~/.cache/mkosi-credstore:/usr/lib/credstore
RemoveFiles=/etc/crypttab
SkeletonTrees=
    /var/lib/pacman/sync:/var/lib/pacman/sync
    /var/cache/pacman/pkg:/var/cache/pacman/pkg
    ~/.local/share/nvim/site:/etc/skel/.local/share/nvim/site
    ~/.cache/yay:/root/.cache/yay
    /etc/pacman.d/mirrorlist:/etc/pacman.d/mirrorlist
    ~/.cargo/registry:/root/.cargo/registry
    ~/.cache/sccache:/root/.cache/sccache
Packages=
    ansible
    archlinux-keyring
    base
    btrfs-progs
    base-devel
    ccid
    efibootmgr
    git
    intel-ucode
    inetutils
    iptables
    iwd
    libfido2
    linux
    linux-firmware
    linux-headers
    lzop
    mkinitcpio
    mkosi
    pacman
    pass
    gnutls
    opensc
    pcsclite
    go
    npm
    python
    python-passlib
    python-pefile
    python-pystache
    python-pip
    python-pylint
    pyright
    ruff
    rust
    rust-analyzer
    rust-src
    typescript-language-server
    sccache
    uv
    rsync
    socat
    sudo
    systemd-resolvconf
    systemd-ukify
    tmux
    tpm2-tss
    vim
    wireguard-tools
    xdg-user-dirs
    wireless_tools
    zsh

