# vim: ft=dosini

[Config]
PassEnvironment=ANSIBLE_EXTRA_ARGS SKIP_POSTINST

[Distribution]
Distribution=arch

[Validation]
Passphrase=mkosi.passphrase

[Build]
WithNetwork=yes
Incremental=yes
BuildSources=
    ../
    ~/.local/share/password-store:password-store
    ~/.cache/yay/yay-bin:yay-pkg

CacheDirectory=~/.cache/mkosi
PackageCacheDirectory=~/.cache/mkosi/pacman-pkg
BuildDirectory=~/.cache/mkosi/build
BuildSourcesEphemeral=buildcache
UseSubvolumes=auto

[Output]
Format=disk
Output=arch
ImageVersion=a
SplitArtifacts=root,uki
RepartDirectories=mkosi.repart

[Content]
KernelCommandLine=rw quiet
BuildScripts=../mkosi.build
BuildPackages=rust
PostInstallationScripts=../mkosi.postinst.chroot
Bootable=yes
Timezone=US/Pacific
Locale=en_US.UTF-8
CleanPackageMetadata=false
SkeletonTrees=
    /var/lib/pacman/sync:/var/lib/pacman/sync
    ~/.cache/mkosi/pacman-pkg:/var/cache/pacman/pkg
    ~/.local/share/nvim:/usr/local/share/nvim
    ~/.cache/yay:/root/.cache/yay
Packages=
    ansible
    archlinux-keyring
    base
    btrfs-progs
    base-devel
    ccid
    efibootmgr
    git
    intel-ucode
    inetutils
    iptables
    iwd
    libfido2
    linux
    linux-firmware
    linux-headers
    lzop
    mkinitcpio
    mkosi
    pacman
    pass
    pcsclite
    go
    npm
    python
    python-passlib
    python-pefile
    python-pystache
    python-pip
    python-pylint
    pyright
    ruff
    rust
    rust-analyzer
    rust-src
    typescript-language-server
    uv
    rsync
    socat
    sudo
    systemd-resolvconf
    systemd-ukify
    tmux
    tpm2-tss
    vim
    wireguard-tools
    xdg-user-dirs
    wireless_tools
    zsh

