# vim:ft=yaml.ansible:
---
- name: Install packages
  package:
    state: present
    name:
      - wl-gammarelay
      - brightnessctl
      - upower

- name: Install day-or-night binary
  copy:
    src: day-or-night
    dest: /usr/lib/arch-ansible/bin/day-or-night
    mode: a+x

- name: Install wl-gammarelay service
  copy:
    src: wl-gammarelay.service
    dest: /usr/lib/systemd/user/wl-gammarelay.service

- name: Enable wl-gammarelay service
  service:
    name: wl-gammarelay.service
    enabled: yes
    scope: global

- name: Install colorscheme-changer binary
  copy:
    src: colorscheme-changer
    dest: /usr/lib/arch-ansible/bin/colorscheme-changer
    mode: a+x

- name: Install colorscheme-changer service
  copy:
    src: colorscheme-changer.service
    dest: /usr/lib/systemd/user/colorscheme-changer.service

- name: Install colorscheme-changer timer
  copy:
    src: colorscheme-changer.timer
    dest: /usr/lib/systemd/user/colorscheme-changer.timer

- name: Enable colorscheme-changer timer
  service:
    name: colorscheme-changer.timer
    enabled: yes
    scope: global
