# vim:ft=yaml.ansible:
---
- name: Install repo system-wide
  synchronize:
    src: "{{ playbook_dir }}/"
    dest: /usr/local/share/arch-ansible/
    delete: true

- name: Install password-store system-wide
  synchronize:
    src: /work/src/password-store/
    dest: /usr/local/share/password-store/
    delete: true
