# vim:ft=yaml.ansible:
---
# Reflector ranks mirrors
- name: Install reflector
  package:
    name: reflector
    state: present

- name: Install reflector service
  copy:
    src: reflector.service
    dest: /etc/systemd/system/reflector.service

- name: Install reflector timer
  copy:
    src: reflector.timer
    dest: /etc/systemd/system/reflector.timer

- name: Enable reflector timer
  service:
    name: reflector.timer
    enabled: yes
