# vim:ft=yaml.ansible:
---
- name: Create kernel module directory
  file:
    path: /etc/modprobe.d
    state: directory

- name: Configure kernel modules
  copy:
    src: "modprobe.d/{{ item }}"
    dest: "/etc/modprobe.d/{{ item }}"
  loop: "{{ modprobe_files }}"

- name: Install mkinitcpio.conf
  template:
    src: mkinitcpio.conf.j2
    dest: /etc/mkinitcpio.conf

- name: Install UKI preset
  copy:
    src: linux.preset
    dest: /etc/mkinitcpio.d/linux.preset

- name: Create UKI output directory
  file:
    path: /efi/EFI/Linux
    state: directory

