[Partition]
Type=root
Format=btrfs
Label=root-a
MountPoint=/:"noatime,compress=zstd:1,discard=async,space_cache=v2"
Encrypt=key-file
CopyFiles=/
ExcludeFiles=/home
ExcludeFiles=/var
SizeMinBytes=20G
SizeMaxBytes=20G
