# vim:ft=yaml.ansible:
---
- name: Install user service
  copy:
    src: udiskie.service
    dest: /usr/lib/systemd/user/udiskie.service

- name: Install systemd user preset
  copy:
    src: 80-udiskie.preset
    dest: /usr/lib/systemd/user-preset/80-udiskie.preset
