# vim:ft=yaml.ansible:
---
# TODO: Make waybars reveal over full screen when screen is touched or mouse is moved

- name: Install package
  package:
    name: waybar
    state: present

- name: Create waybar config dir
  file:
    path: /etc/xdg/waybar
    state: directory

- name: Install waybar config
  template:
    src: waybar-config.json.j2
    dest: /etc/xdg/waybar/config
  tags: [base16]

- name: Install waybar styling
  template:
    src: waybar-style.css.j2
    dest: /etc/xdg/waybar/style.css
  tags: [base16]

- name: Install service
  copy:
    src: waybar.service
    dest: /etc/systemd/user/waybar.service

- name: Enable service
  become: true
  become_user: "{{ user.name }}"
  systemd:
    enabled: true
    name: waybar.service
    scope: global
    daemon-reload: "{{ svc_daemon_reload }}"

- name: Create waybar-sway-workspace-output-manager config dir
  file:
    path: /etc/xdg/waybar-sway-workspace-output-manager
    state: directory

- name: Install waybar-sway-workspace-output-manager config file
  template:
    src: waybar-sway-workspace-output-manager-config.j2
    dest: /etc/xdg/waybar-sway-workspace-output-manager/config
  tags: [base16]

- name: Install waybar-sway-workspace-output-manager service
  copy:
    src: waybar-sway-workspace-output-manager.service
    dest: /etc/systemd/user/waybar-sway-workspace-output-manager.service

- name: Enable waybar-sway-workspace-output-manager service
  become: true
  become_user: "{{ user.name }}"
  systemd:
    enabled: true
    name: waybar-sway-workspace-output-manager.service
    scope: global
    daemon-reload: "{{ svc_daemon_reload }}"

- name: Install module scripts
  copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: a+x
  with_items:
    - waybar-bluetooth-status
    - toggle-bluetooth
    - toggle-wifi
    - toggle-eeek-vpn
    - eeek-vpn-status
    - headphone-profile-status
