[Partition]
Type=root
Format=btrfs
MountOptions=subvol=@,noatime,compress=zstd:1,discard=async,space_cache=v2
Encrypt=key-file
CopyFiles=/
Minimize=best
DefaultSubvolume=/@
Subvolumes=/@
           /@home
           /@snapshots
           /@var_log
           /@var_cache
           /@var_tmp
MakeDirectories=/.snapshots
MkfsOptions=-L root
