[Partition]
Type=var
Format=btrfs
Label=var
MountPoint=/var:"noatime,compress=zstd:1,discard=async,space_cache=v2"
Subvolumes=/log /cache /tmp
Encrypt=key-file
EncryptedVolume=var:"/etc/cryptsetup-keys.d/luks.passphrase"
CopyFiles=/var:/
SizeMinBytes=10G
