[Include]
Include=../../mkosi.common

[Output]
ImageId=qemu
RepartDirectories=
    ../../mkosi.common/mkosi.repart
    mkosi.repart

[Runtime]
RuntimeSize=40G

[Content]
Packages=
    qemu-guest-agent
