#!/usr/bin/env python

import os
import socket
import subprocess
import sys


def _reload_wayland():
    for service in ["waybar.service", "waybar-sway-workspace-output-manager.service"]:
        subprocess.run(["systemctl", "--user", "restart", service], check=True)

    subprocess.run(["swaymsg", "reload"])


def _reload_xorg():
    subprocess.run(["systemctl", "--user", "restart", "feh.service"], check=True)
    subprocess.run(["i3-msg", "reload"])


def main():
    env = dict(os.environ)
    env["NO_ASK_BECOME_PASS"] = "1"
    ansible_result = subprocess.run(
        ["nice", "./ansible", "--tags", "base16"],
        capture_output=True,
        cwd=os.path.join(os.path.expanduser("~"), "src", "arch-ansible"),
        encoding="utf-8",
        env=env,
    )

    if ansible_result.returncode != 0:
        print("Ansible run failed: {}".format(ansible_result.stderr))
        sys.exit(ansible_result.returncode)

    if "changed=0" in ansible_result.stdout:
        print("No change from ansible run, exiting")
        return

    print("Running reloads")
    # TODO: Reload running tmuxen
    # TODO: Realod running nvims
    if os.environ["XDG_SESSION_TYPE"] == "wayland":
        _reload_wayland()
    else:
        _reload_xorg()


if __name__ == "__main__":
    main()
