#!/usr/bin/env python

import os
import subprocess
import sys


def _reload_wayland():
    subprocess.run(
        [
            "systemctl",
            "--user",
            "restart",
            "waybar-sway-workspace-output-manager.service",
        ],
        check=True,
    )
    subprocess.run(["systemctl", "--user", "reload", "waybar"], check=True)

    subprocess.run(["swaymsg", "reload"])


def main():
    env = dict(os.environ)
    env["NO_ASK_BECOME_PASS"] = "1"
    ansible_result = subprocess.run(
        ["nice", "./bin/ansible", "--tags", "base16"],
        capture_output=True,
        cwd=os.path.join(os.path.expanduser("~"), "src", "arch-ansible"),
        encoding="utf-8",
        env=env,
    )

    if ansible_result.returncode != 0:
        print("Ansible run failed: {}".format(ansible_result.stderr))
        sys.exit(ansible_result.returncode)

    if "changed=0" in ansible_result.stdout:
        print("No change from ansible run, exiting")
        return

    print("Running reloads")
    # TODO: Reload running tmuxen
    # TODO: Realod running nvims
    if os.environ["XDG_SESSION_TYPE"] == "wayland":
        _reload_wayland()
    else:
        print("can only run under wayland")
        sys.exit(1)


if __name__ == "__main__":
    main()
