#!/bin/bash

set -o errexit
set -o nounset

printf "🎧"
if pactl list | grep -q "Active Profile: a2dp-sink-aac" ; then
  printf "🎶"
elif pactl list | grep -q "Active Profile: headset-head-unit-msbc" ; then
  printf "🎤"
else
  printf "❎"
fi

printf "\n"
