#!/bin/bash

set -o errexit
set -o nounset

if pactl list | grep -q "Active Profile: a2dp-sink" ; then
  printf "󰋋🎶"
elif pactl list | grep -q "Active Profile: headset-head-unit" ; then
  printf "󰋋󰍮"
else
  printf "󰟎"
fi

printf "\n"
