#!/bin/bash

set -o errexit
set -o nounset

if ! command -v yay >/dev/null; then
  tmp=$(mktemp -d)
  function finish {
    rm -rf "$tmp"
  }
  trap finish EXIT

  pushd $tmp
  git clone https://aur.archlinux.org/yay.git
  cd yay
  makepkg --needed --noconfirm --skippgpcheck -sri
  popd

  if ! command -v yay >/dev/null; then
    >&2 echo "Yay wasn't successfully installed"
    exit 1
  fi
fi
