#!/bin/bash

set -o errexit
set -o nounset

if ! command -v yay >/dev/null; then
  tmp=$(mktemp -d)
  function finish {
    rm -rf "$tmp"
  }
  trap finish EXIT

  pushd $tmp
  for pkg in cower yay; do
    curl -o PKGBUILD https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=$pkg && \
      makepkg --needed --noconfirm --skippgpcheck -sri
  done
  popd

  if ! command -v yay >/dev/null; then
    >&2 echo "Yay wasn't successfully installed"
    exit 1
  fi
fi
