#! /bin/zsh

set -o errexit
set -o nounset
set -o pipefail

get_selection() {
  {rg --files ; print -rl -- ${(ko)commands}} | fzf
}

selection=$(get_selection)
if command -v $selection > /dev/null >&1 ; then
  nohup $selection > /dev/null 2>&1 &
  sleep 0.1
else
  xdg-open $selection
fi
