#!/usr/bin/env python

import re
import subprocess


def main():
    redshift_print_result = subprocess.run(
        ["redshift", "-p"], check=True, capture_output=True, encoding="utf-8"
    )

    # String looks like one of the following:
    #  * Period: Daytime
    #  * Period: Night
    #  * Period: Transition (2.05% day)
    #  * Period: None
    period_match = re.search(
        r"Period: ([a-zA-Z]+)( \((.*)% .*\))*", redshift_print_result.stdout
    )
    if period_match is None:
        raise RuntimeError(
            "No period found in redshift print output: {}".format(
                redshift_print_result.stdout
            )
        )

    if period_match.group(1) == "None":
        print("night", end="")
        return

    if period_match.group(1) != "Transition":
        print(period_match.group(1).lower(), end="")
        return

    percent_daytime = float(period_match.group(3))
    if percent_daytime >= 50:
        print("daytime", end="")
    else:
        print("night", end="")

    return


if __name__ == "__main__":
    main()
