#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

export RESTIC_REPOSITORY="b2:mnussbaum-machine-backups"
hostname_short="$(hostname -s)"
export B2_ACCOUNT_KEY="$(cat "${CREDENTIALS_DIRECTORY}/${hostname_short}_restic_backblaze_key")"
export B2_ACCOUNT_ID="$(cat "${CREDENTIALS_DIRECTORY}/${hostname_short}_restic_backblaze_key_id")"
export RESTIC_PASSWORD_FILE="${CREDENTIALS_DIRECTORY}/restic_backup_password"

# I manually ran "restic init" with these configs first

exec restic backup \
    --compression max \
    --exclude-caches \
    --one-file-system \
    --cleanup-cache \
    ~/Sync \
    ~/Documents \
    ~/Camera \
    ~/tiktoks
