#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

export RESTIC_REPOSITORY="b2:mnussbaum-machine-backups"
export B2_ACCOUNT_KEY="$(pass backblaze_keys/bodie_restic_backup_key)"
export B2_ACCOUNT_ID="$(pass backblaze_keys/bodie_restic_backup_key_id)"
export RESTIC_PASSWORD_COMMAND="pass show restic_backup_password"

# I manually ran "restic init" with these configs first

exec restic backup \
    --compression max \
    --exclude-caches \
    --one-file-system \
    --cleanup-cache \
    ~/Sync \
    ~/Documents
