#!/usr/bin/bash

set -o nounset

invoking_rofi_pass=false
if grep -q rofi-pass <<< "$@" ; then
  invoking_rofi_pass=true
fi

pgrep --exact --full 'bash /usr/bin/rofi-pass' >/dev/null 2>/dev/null
running_rofi_pass=$?
if $invoking_rofi_pass && [ $running_rofi_pass == 0 ] ; then
  pkill --exact rofi
  exit 0
fi

if $invoking_rofi_pass ; then
  pkill --exact rofi
  exec $@
fi

# If we're running rofi-pass then kill it and start new rofi command
if [ $running_rofi_pass == 0 ] && pkill --exact rofi ; then
  exec $@
fi

# If we're running normal rofi then kill it, if we aren't then start it
if ! pkill --exact --full "$@" ; then
  exec $@
fi
