#!/bin/bash

warp_status=$(warp-cli status 2> /dev/null)

if [[ $warp_status != *"Status update: Connected"* ]]; then
  systemctl start warp-svc
  sleep 1
  warp-cli connect > /dev/null
else
  warp-cli disconnect > /dev/null
  systemctl stop warp-svc
fi
