#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

bluetooth_device_id=$(
  rfkill --json | \
    jq '.rfkilldevices | map(select(.type == "bluetooth")) | map(.id) | first'
)

pkexec rfkill toggle $bluetooth_device_id
