#! /bin/sh

# Waits for internet connectivity

set -o errexit
set -o nounset

while [ "$(ip -oneline link show  up)" != "$(ip -oneline link show)" ] ; do
  >&2 echo "Not all network interfaces up yet"
  sleep 1
done

echo "All network interfaces up"

until curl --silent --fail --max-time 1 https://www.google.com >/dev/null 2>/dev/null; do
  >&2 echo "Curl https://www.google.com failed"
  sleep 1
done

echo "Successfully reached https://www.google.com"
