# vim:ft=yaml.ansible:
---
- name: Create config dirs
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/sway
    - /etc/sway/config.d
    - /etc/swaylock
    - /etc/xdg/mako
  tags: [base16]

- name: Install sway env file
  copy:
    src: sway-env
    dest: /etc/sway/env

- name: Install sway packages
  package:
    state: present
    name:
      - mesa
      - sway
      - swaybg
      - swayidle
      - swaylock
      - chayang
      - libnotify
      - mako
      - wl-clipboard
      - glfw-wayland # Provides libs for GLFW apps
      - grim
      - slurp
      - satty
      - xorg-xwayland
      - wdisplays
      - thunar
      - tumbler # thumbnails for thunar

- name: Generate base16 configs
  base16_builder:
    scheme: "{{ base16_scheme }}"
    scheme_family: "{{ base16_scheme_family }}"
    template: i3
    schemes_source: "{{ base16['schemes_source'] }}"
    templates_source: "{{ base16['templates_source'] }}"
  register: base16_i3
  tags: [base16]

- name: Install config
  template:
    src: sway_config.j2
    dest: /etc/sway/config
  tags: [base16]

- name: Install swaylock config
  template:
    src: swaylock_config.j2
    dest: /etc/swaylock/config
  tags: [base16]

- name: Generate mako base16 config
  base16_builder:
    scheme: "{{ base16_scheme }}"
    scheme_family: "{{ base16_scheme_family }}"
    template: mako
    schemes_source: "{{ base16['schemes_source'] }}"
    templates_source: "{{ base16['templates_source'] }}"
  register: base16_mako
  tags: [base16]

- name: Write mako config to a file
  template:
    src: mako.j2
    dest: /etc/xdg/mako/config
  tags: [base16]

- name: Install services
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/user/{{ item }}"
  with_items:
    - sway-session.target
    - sway.service

- name: Install swayidle service
  template:
    src: swayidle.service.j2
    dest: "/etc/systemd/user/swayidle.service"

- name: Install systemd user preset
  copy:
    src: 80-sway.preset
    dest: /usr/lib/systemd/user-preset/80-sway.preset

