---
disk:
  device: /dev/nvme0n1

mkinitcpio_modules:
  - nvme_core
  - nvme
  - intel_agp
  - i915

modprobe_files:
  - i915.conf
  - iwlwifi.conf
  - nvme.conf
  - no-psmouse.conf

key_repeat:
  rate: 35
  delay: 250

window_manager:
  waybar_minimum_workspace_count: 5
  window_manager: sway
  windowing_system: wayland

qemu_host: true

pgpass_secret_names:
  - eq/pgpass
