---
grub: true

partitions:
  efi:
    number: 1
    physical_device: /dev/nvme0n1
    partition_device: /dev/nvme0n1p1
    logical_device: /dev/nvme0n1p1
    partition_name: EFI system partitions
    partition_label: gpt
    start: 1MiB
    end: 241MiB
    fstype: vfat
    fs_options: ""
    mount_point: /mnt/boot/efi
    encrypted: false
    managed: false
    flags:
      - boot
      - esp
  boot:
    number: 7
    physical_device: /dev/nvme0n1
    partition_device: /dev/nvme0n1p7
    logical_device: /dev/nvme0n1p7
    partition_name: Grub
    partition_label: gpt
    start: 28979MiB
    end: 29467MiB
    fstype: ext4
    fs_options: "-O ^has_journal"
    mount_point: /mnt/boot
    encrypted: false
    managed: true
    flags: []
  root:
    number: 8
    physical_device: /dev/nvme0n1
    partition_device: /dev/nvme0n1p8
    logical_device: /dev/mapper/vgcrypt-root
    volume_group_name: vgcrypt
    logical_volume_name: root
    partition_name: Arch Root
    partition_label: gpt
    start: 29467MiB
    end: 957726MiB
    fstype: ext4
    fs_options: "-O ^has_journal"
    mount_point: /mnt
    encrypted: true
    managed: true
    flags: []

mkinitcpio_modules:
  - nvme_core
  - nvme
  - intel_agp
  - i915

modprobe_files:
  - i915.conf
  - iwlwifi.conf
  - nvme.conf

networking:
  wireless_interface: wlp0s20f3

  networks:
    - ssid: "JazzHandz"
      password: "{{ wifi_passwords['jazz_hands'] }}"
    - ssid: "No Pants No Problems"
      password: "{{ wifi_passwords['no_pants_no_problems'] }}"
    - ssid: "HOME-0959-2.4"
      password: "{{ wifi_passwords['rehoboth'] }}"
    - ssid: "nuttree"
      password: "{{ wifi_passwords['bethesda'] }}"
    - ssid: "Sonic-3913"
      password: "{{ wifi_passwords['gens'] }}"
    - ssid: "Lilypad"
      password: "{{ wifi_passwords['joyces'] }}"
    - ssid: "CBCI-9388"
      password: "canvas3356baked"
    - ssid: "Blue_Skye"
      password: "HomeSweetHome_555"
    - ssid: "FourSeasons"
    # ssid="WeWorkWiFi"
    # key_mgmt=WPA-EAP
    # eap=PEAP
    # identity="mike@equilibriumenergy.com"
    # password="sod-dine-ante-moody"
    # phase2="auth=MSCHAPV2"

key_repeat:
  rate: 35
  delay: 250

monitors:
  - id: eDP-1
    position:
      x: 0
      y: 0
    scale: 2
  - id: DP-1
    position:
      x: -1100
      y: -1600
    scale: 0.9

firefox:
  hidpi: true

optional_daemons:
  clightd: false
  libinput_gestures: false

window_manager:
  waybar_minimum_workspace_count: 5
  window_manager: sway
  windowing_system: wayland

qemu_host: false
