---
grub: false

partitions:
  boot:
    number: 1
    physical_device: /dev/mmcblk0
    partition_device: /dev/mmcblk0p1
    partition_label: msdos
    logical_device: /dev/mmcblk0p1
    start: 0%
    end: 300MiB
    fstype: vfat
    mount_point: /tmp/panamint-boot
    encrypted: false
    flags:
      - lba
      - boot
  root:
    number: 2
    physical_device: /dev/mmcblk0
    partition_device: /dev/mmcblk0p2
    partition_label: msdos
    logical_device: /dev/mapper/pi-sd-root
    volume_group_name: pi-sd-root
    start: 300MiB
    end: 100%
    fstype: ext4
    mount_point: /var/lib/machines/panamint
    encrypted: true
    flags: []

mkinitcpio:
  modules:
    - g_cdc
    - usb_f_acm
    - usb_f_ecm
    - smsc95xx
    - g_ether
  hooks:
    - base
    - udev
    - autodetect
    - modconf
    - block
    - consolefont
    - keyboard
    - encrypt
    - lvm2
    - sleep
    - netconf
    - dropbear
    - encryptssh
    - filesystems
    - fsck

modprobe_files: []

key_repeat:
  delay: 250

firefox:
  package: firefox
  hidpi: false

optional_daemons:
  clightd: false
  libinput_gestures: false

user:
  name: mnussbaum
  group: mnussbaum
  shell: /usr/bin/zsh
  email: michaelnussbaum08@gmail.com

network:
  ssid: "JazzHands2.4G"
  wireless_interface: wlan0

window_manager:
  window_manager: sway
  windowing_system: wayland

monitors:
  - id: HDMI-A-1
    position:
      x: 0
      y: 0
    scale: 2

qemu_host: false
