---
disk:
  device: /dev/sda
  partition_uuid: 669ab9d2-2cac-4690-bf87-03cdc177fb45

mkinitcpio_modules:
  - nvme
  - intel_agp
  - i915

modprobe_files:
  - i915.conf
  - iwlwifi.conf
  - nvme.conf

key_repeat:
  rate: 35
  delay: 250

monitors:
  id: Virtual-1

optional_daemons:
  libinput_gestures: false

window_manager:
  waybar_minimum_workspace_count: 5
  window_manager: sway
  windowing_system: wayland

qemu_host: false

networking:
  interface: enp0s2
