---
grub: true

partitions:
  efi:
    number: 1
    physical_device: /dev/sda
    partition_device: /dev/sda1
    logical_device: /dev/sda1
    partition_name: EFI
    partition_label: gpt
    start: 0%
    end: 261MiB
    fstype: vfat
    fs_options: ""
    mount_point: /mnt/boot/efi
    encrypted: false
    flags:
      - esp
  boot:
    number: 2
    physical_device: /dev/sda
    partition_device: /dev/sda2
    logical_device: /dev/sda2
    partition_name: Grub
    partition_label: gpt
    start: 261MiB
    end: 773MiB
    fstype: ext4
    fs_options: "-O ^has_journal"
    mount_point: /mnt/boot
    encrypted: false
    flags: []
  root:
    number: 3
    physical_device: /dev/sda
    partition_device: /dev/sda3
    logical_device: /dev/mapper/vgcrypt-root
    volume_group_name: vgcrypt
    logical_volume_name: root
    partition_name: Arch Root
    partition_label: gpt
    start: 773MiB
    end: 100%
    fstype: ext4
    fs_options: "-O ^has_journal"
    mount_point: /mnt
    encrypted: true
    flags: []

mkinitcpio:
  modules:
    - nvme
    - intel_agp
    - i915
  hooks:
    - base
    - udev
    - autodetect
    - modconf
    - block
    - consolefont
    - keymap
    - keyboard
    - encrypt
    - resume
    - lvm2
    - filesystems
    - fsck

modprobe_files:
  - intel.conf
  - iwlwifi.conf
  - nvme.conf

key_repeat:
  delay: 250

monitors:
  id: Virtual-1

firefox:
  package: firefox-nightly
  hidpi: false

optional_daemons:
  clightd: false
  libinput_gestures: false

user:
  name: mnussbaum
  group: mnussbaum
  shell: /usr/bin/zsh
  email: michaelnussbaum08@gmail.com

window_manager:
  window_manager: sway
  windowing_system: wayland

qemu_host: false
