---
grub: true

partitions:
  boot:
    number: 7
    physical_device: /dev/nvme0n1
    partition_device: /dev/nvme0n1p7
    logical_device: /dev/nvme0n1p7
    partition_name: Grub
    partition_label: gpt
    start: 77414MiB
    end: 77902MiB
    fstype: ext4
    fs_options: "-O ^has_journal"
    mount_point: /mnt/boot
    encrypted: false
    flags: []
  root:
    number: 8
    physical_device: /dev/nvme0n1
    partition_device: /dev/nvme0n1p8
    logical_device: /dev/mapper/vgcrypt-root
    volume_group_name: vgcrypt
    logical_volume_name: root
    partition_name: Arch Root
    partition_label: gpt
    start: 77902MiB
    end: 476822MiB
    fstype: ext4
    fs_options: "-O ^has_journal"
    mount_point: /mnt
    encrypted: true
    flags: []

mkinitcpio_modules:
  - nvme
  - intel_agp
  - i915

modprobe_files:
  - intel.conf
  - iwlwifi.conf
  - nvme.conf

networking:
  wireless_interface: wlp60s0
  networks:
    - ssid: "JazzHands2.4G"
      password: "{{ wifi_passwords['jazz_hands'] }}"
    - ssid: "WiFi By The Sea"
      password: "{{ wifi_passwords['wifi_by_the_sea'] }}"
    - ssid: "HOME-0959-2.4"
      password: "{{ wifi_passwords['rehoboth'] }}"
    - ssid: "nuttree"
      password: "{{ wifi_passwords['bethesda'] }}"
    - ssid: "Sonic-3913"
      password: "{{ wifi_passwords['gens'] }}"

key_repeat:
  rate: 35
  delay: 250

monitors:
  - id: eDP-1
    position:
      x: 0
      y: 0
    scale: 2
  - id: DP-1
    position:
      x: -1100
      y: -1600
    scale: 0.9

firefox:
  hidpi: true

optional_daemons:
  clightd: true
  libinput_gestures: true

window_manager:
  waybar_minimum_workspace_count: 5
  window_manager: sway
  windowing_system: wayland

qemu_host: true
