---
disk:
  device: /dev/nvme0n1

mkinitcpio_modules:
  - nvme_core
  - nvme
  - intel_agp
  - i915

modprobe_files:
  - i915.conf
  - iwlwifi.conf
  - nvme.conf

networking:
  interface: wlp60s0
  networks:
    - ssid: "JazzHandz"
      psk: "{{ wifi_passwords['jazz_hands'] }}"
    - ssid: "Buns of Steel"
      psk: "{{ wifi_passwords['buns_of_steel'] }}"
    - ssid: "HOME 0959-2.4"
      psk: "{{ wifi_passwords['rehoboth'] }}"
    - ssid: "nuttree"
      psk: "{{ wifi_passwords['bethesda'] }}"
    - ssid: "Sonic-3913"
      psk: "{{ wifi_passwords['gens'] }}"
    - ssid: "Lilypad"
      psk: "{{ wifi_passwords['joyces'] }}"
    - ssid: "wmvnet"
      psk: "{{ wifi_passwords['varneys'] }}"
    - ssid: "WeWorkWiFi"
      key_mgmt: "WPA-EAP"
      eap: "PEAP"
      identity: "mike@equilibriumenergy.com"
      password: "{{ wifi_passwords['we_work'] }}"
      phase2: "MSCHAPV2"

key_repeat:
  rate: 35
  delay: 250

monitors:
  - id: eDP-1
    position:
      x: 950
      y: 1600
    scale: 2
  - id: ASUSTek COMPUTER INC PA34V KBLMQS025309
    position:
      x: 0
      y: 0
    scale: 0.9
  # For TV
  # - id: DP-1
  #   position:
  #     x: -10100
  #     y: -10600
  #   scale: 1

window_manager:
  waybar_minimum_workspace_count: 5
  window_manager: sway
  windowing_system: wayland

qemu_host: true

pgpass_secret_names:
  - eq/pgpass
