---
desired_partitions:
  - number: 7
    physical_device: "/dev/nvme0n1"
    partition_device: "/dev/nvme0n1p7"
    logical_device: "/dev/nvme0n1p7"
    name: Grub
    start: 77414MiB
    end: 77902MiB
    fstype: ext4
    fs_options: "-O ^has_journal"
    mount_point: "/mnt/boot"
    encrypted: false
    flags: []
  - number: 8
    physical_device: "/dev/nvme0n1"
    partition_device: "/dev/nvme0n1p8"
    logical_device: "/dev/mapper/vgcrypt-root"
    name: Arch Root
    start: 77902MiB
    end: 476822MiB
    fstype: ext4
    fs_options: "-O ^has_journal"
    mount_point: "/mnt"
    encrypted: true
    volume_container_name: lvm
    volume_group_name: vgcrypt
    logical_volume_name: root
    flags: []

network:
  ssid: "JazzHands"
  wireless_card: wlp60s0

key_repeat:
  delay: 250

monitors:
  - id: eDP-1
    position:
      x: 0
      y: 0
    scale: 2
  - id: DP-1
    position:
      x: -1100
      y: -1600
    scale: 0.9

hidpi_firefox: true

optional_daemons:
  clightd: true
  libinput_gestures: true

user:
  name: mnussbaum
  group: mnussbaum
  shell: /usr/bin/zsh
  email: michaelnussbaum08@gmail.com

window_manager:
  window_manager: sway
  windowing_system: wayland
