---
disk:
  device: /dev/sda

mkinitcpio_modules:
  - nvme
  - intel_agp
  - i915

modprobe_files:
  - i915.conf
  - iwlwifi.conf
  - nvme.conf

key_repeat:
  rate: 35
  delay: 250

monitors:
  - id: eDP-1
    position:
      x: 0
      y: 0
    scale: 1

window_manager:
  waybar_minimum_workspace_count: 5
  window_manager: sway
  windowing_system: wayland

qemu_host: false

networking:
  interface: wlan0
  networks:
    - ssid: "JazzHandz"
      psk: "{{ wifi_passwords['jazz_hands'] }}"
    - ssid: "Buns of Steel"
      psk: "{{ wifi_passwords['buns_of_steel'] }}"
    - ssid: "HOME 0959-2.4"
      psk: "{{ wifi_passwords['rehoboth'] }}"
    - ssid: "nuttree"
      psk: "{{ wifi_passwords['bethesda'] }}"
    - ssid: "Sonic-3913"
      psk: "{{ wifi_passwords['gens'] }}"
    - ssid: "Lilypad"
      psk: "{{ wifi_passwords['joyces'] }}"
    - ssid: "wmvnet"
      psk: "{{ wifi_passwords['varneys'] }}"
    - ssid: "Codi 7th Floor"
      psk: "{{ wifi_passwords['codi_seventh_floor'] }}"
    - ssid: "WeWorkWiFi"
      key_mgmt: "WPA-EAP"
      eap: "PEAP"
      identity: "mike@equilibriumenergy.com"
      password: "{{ wifi_passwords['we_work'] }}"
      phase2: "auth=MSCHAPV2"
