---
grub: true

desired_partitions:
  boot:
    number: 1
    physical_device: "/dev/sda"
    partition_device: "/dev/sda1"
    logical_device: "/dev/sda1"
    partition_name: Grub
    partition_label: gpt
    start: 0%
    end: 261MiB
    fstype: ext4
    fs_options: "-O ^has_journal"
    mount_point: "/mnt/boot"
    encrypted: false
    flags: []
  root:
    number: 2
    physical_device: "/dev/sda"
    partition_device: "/dev/sda2"
    logical_device: "/dev/mapper/vgcrypt-root"
    partition_name: Arch Root
    partition_label: gpt
    start: 261MiB
    end: 100%
    fstype: ext4
    fs_options: "-O ^has_journal"
    mount_point: "/mnt"
    encrypted: false
    flags: []

mkinitcpio_modules: []
modprobe_files: []

key_repeat:
  delay: 350

monitors:
  id: VGA-1

hidpi_firefox: false

optional_daemons:
  clightd: true
  libinput_gestures: true

user:
  name: vagrant
  group: vagrant
  shell: /usr/bin/zsh
  email: foo@bar.com

window_manager:
  window_manager: i3
  windowing_system: x11
