# vim:ft=yaml.ansible:
---
- name: Install packages
  package:
    state: present
    name:
      - qemu-desktop
      - edk2-ovmf
      - sdl2
      - socat
      - swtpm

- name: Enable kvm CPU pass-through
  copy:
    content: "options kvm_intel nested=1"
    dest: "/usr/lib/modprobe.d/kvm_intel.conf"

- name: Enable virtio module
  copy:
    content: "virtio"
    dest: "/usr/lib/modules-load.d/virtio.conf"

- name: Enable vhost_vsock module
  copy:
    content: "vhost_vsock"
    dest: "/usr/lib/modules-load.d/vhost_vsock.conf"

- name: Install systemd preset
  copy:
    src: 80-qemu-host.preset
    dest: /usr/lib/systemd/system-preset/80-qemu-host.preset

- name: Deploy pcscd vsock forwarding service
  copy:
    src: pcscd-vsock-host.service
    dest: /usr/lib/systemd/system/pcscd-vsock-host.service
    mode: "0644"
