# vim:ft=yaml.ansible:
---
- name: Create arch-images directory
  file:
    path: ~/.local/share/arch-images
    state: directory
    mode: "0750"

- name: Check nodatacow attribute on arch-images directory
  command: lsattr -d ~/.local/share/arch-images
  register: arch_images_attrs
  changed_when: false

- name: Disable CoW on arch-images directory
  become: true
  command: chattr +C ~/.local/share/arch-images
  when: "'C' not in arch_images_attrs.stdout.split()[0]"
