[UKIProfile]
Profile=
        ID=live
        TITLE=Live System

Cmdline=
        root=tmpfs
        mount.usr=dissect
        rd.systemd.mask=systemd-repart.service
        systemd.mask=systemd-repart.service
        systemd.set-credential=passwd.plaintext-password.root:root
        systemd.set-credential=agetty.autologin:root
        systemd.set-credential=login.noauth:yes
        SYSTEMD_SULOGIN_FORCE=1
        rw
        audit=0
        systemd.image_policy=esp=unprotected:xbootldr=unprotected+unused+absent:usr=signed:=ignore
        systemd.image_filter=usr=image_*:usr-verity=image_*:usr-verity-sig=image_*
        ipe.enforce=0

SignExpectedPcr=no
