[UKIProfile]
Profile=
        ID=install
        TITLE=Installer

Cmdline=
        root=tmpfs
        mount.usr=dissect
        rd.systemd.mask=systemd-repart.service
        systemd.mask=systemd-repart.service
        systemd.unit=systemd-sysinstall.service
        systemd.set-credential=passwd.plaintext-password.root:root
        rw
        audit=0
        systemd.image_policy=esp=unprotected:xbootldr=unprotected+unused+absent:usr=signed:=ignore
        systemd.image_filter=usr=image_*:usr-verity=image_*:usr-verity-sig=image_*
        ipe.enforce=0

SignExpectedPcr=no
