# Plaintext home; the full-disk-encryption profile sets its own policy.
[Match]
Profiles=!full-disk-encryption

[Content]
KernelCommandLine=
    systemd.image_policy=esp=unprotected:xbootldr=unprotected+unused+absent:usr=signed:root=encrypted+absent:swap=encrypted+unused+absent:home=unprotected+absent:=ignore
