# vim:ft=yaml.ansible:
---
- name: Install packages
  package:
    state: present
    name:
      - ccid
      - gnupg
      - imagemagick
      - paperkey
      - pcsclite
      - pinentry-curses
      - qrencode
      - yubikey-manager
      - zbar

- name: Install pinentry wrapper
  copy:
    src: pinentry-auto
    dest: /usr/local/bin/pinentry-auto
    mode: "0755"

- name: Install systemd preset
  copy:
    src: 80-gpg.preset
    dest: /usr/lib/systemd/system-preset/80-gpg.preset
