# vim:ft=yaml.ansible:
---
- name: Install gnome polkit agent package
  package:
    state: present
    name: polkit-gnome

# This allows the machinectl connection plugin used to bootstrap Rasp-pi hosts
# to run without requiring the entire playbook to be run as root
- name: Allow all users to run machinectl commands
  copy:
    src: polkit-00-machinectl.rules
    dest: /etc/polkit-1/rules.d/00-machinectl.rules

- name: Install user agent service
  copy:
    src: polkit-gnome-authentication-agent.service
    dest: /etc/systemd/user/polkit-gnome-authentication-agent.service

- name: Install systemd user preset
  copy:
    src: 80-polkit.preset
    dest: /usr/lib/systemd/user-preset/80-polkit.preset

- name: Enable user agent service
  systemd:
    enabled: true
    name: polkit-gnome-authentication-agent.service
    scope: global
