# vim:ft=yaml.ansible:
---
- name: Install packages
  package:
    state: present
    name:
      - postgresql

- name: Create psql config dir
  file:
    path: /etc/xdg/psql
    state: directory

- name: Install psqlrc file
  copy:
    src: psqlrc
    dest: /etc/xdg/psql/psqlrc
