# vim:ft=yaml.ansible:
---
- name: Install packages
  package:
    state: present
    name:
      - syncthing

- name: Create systemd service override dir
  file:
    path: /etc/systemd/user/syncthing.service.d
    state: directory

- name: Add systemd override to set Nice=19
  copy:
    dest: /etc/systemd/user/syncthing.service.d/10-low-priority.conf
    content: |
      [Service]
      Nice=19
      IOSchedulingClass=2
      IOSchedulingPriority=7

- name: Install systemd user preset
  copy:
    src: 80-syncthing.preset
    dest: /usr/lib/systemd/user-preset/80-syncthing.preset

- name: Enable syncthing user service
  when: ansible_facts["virtualization_role"] != "guest"
  systemd:
    enabled: true
    name: syncthing.service
    scope: global
