# vim:ft=yaml.ansible:
---
- name: Install packages
  package:
    state: present
    name:
      - claude-code

- name: Create skel claude config dir
  file:
    path: /etc/skel/.claude
    state: directory

- name: Install settings into skel
  copy:
    src: claude_settings.json
    dest: /etc/skel/.claude/settings.json
