# vim:ft=yaml.ansible:
---
- name: Create theme directory
  file:
    path: "{{ grub_theme_dir }}"
    state: directory
    mode: a+rw

- name: Create icon directory
  file:
    path: "{{ grub_theme_dir }}/icons"
    state: directory

- name: Install theme file
  tags: [base16]
  template:
    src: grub-theme.txt.j2
    dest: "{{ grub_theme_dir }}/custom.txt"

# Grub theme assets sourced from https://github.com/vinceliuice/grub2-themes
# Grub theme guide http://wiki.rosalab.ru/en/index.php/Grub2_theme_tutorial
# Commands to generate Grub fonts defined near font vars

- name: Install theme fonts
  ansible.posix.synchronize:
    src: assets/grub-theme/fonts/
    dest: "{{ grub_theme_dir }}"
    perms: false

- name: Install theme selection assets
  ansible.posix.synchronize:
    src: assets/grub-theme/select/
    dest: "{{ grub_theme_dir }}"
    perms: false

- name: Install theme icons
  ansible.posix.synchronize:
    src: assets/grub-theme/icons/
    dest: "{{ grub_theme_dir }}/icons"
    perms: false

- name: Install theme wallpaper
  ansible.posix.synchronize:
    src: assets/wallpaper/
    dest: "{{ grub_theme_dir }}"
    perms: false
