# vim:ft=yaml.ansible:
---
- name: Install packages
  package:
    state: present
    name:
      - cairo
      - fontconfig
      - freetype2
      - gsfonts
      - libxft
      - ttf-cascadia-code
      - ttf-noto-nerd
      - noto-fonts-emoji
      - gucharmap

- name: Enable LCD filter
  file:
    src: /usr/share/fontconfig/conf.avail/11-lcdfilter-default.conf
    dest: /etc/fonts/conf.d/11-lcdfilter-default.conf
    state: link

- name: Enable sub-pixel rendering
  file:
    src: /usr/share/fontconfig/conf.avail/10-sub-pixel-rgb.conf
    dest: /etc/fonts/conf.d/10-sub-pixel-rgb.conf
    state: link

- name: Disable slight hinting default
  file:
    path: /etc/fonts/conf.d/10-hinting-slight.conf
    state: absent

- name: Enable crisper fonts with full hinting
  file:
    src: /usr/share/fontconfig/conf.avail/10-hinting-full.conf
    dest: /etc/fonts/conf.d/10-hinting-full.conf
    state: link

- name: Disable bitmap fonts
  file:
    src: /usr/share/fontconfig/conf.avail/70-no-bitmaps.conf
    dest: /etc/fonts/conf.d/70-no-bitmaps.conf
    state: link

- name: Enable subpixel autohinting with freetype2
  copy:
    src: freetype2-overrides.sh
    dest: /etc/profile.d/freetype2-overrides.sh
    mode: "0644"

- name: Set font family choices
  template:
    src: fonts-local.conf.j2
    dest: /etc/fonts/local.conf
